### ISSUE TITLE
Incorrect Cosigner Block Order in Multisig wsh String

### ISSUE THREAD

**Issue by PitBullCH** [sparrowwallet/sparrow#1018]
Mac Studio M1 Ultra, MacOS Ventura 13.4 (fully patched), latest Sparrow 1.7.7.

I created a 2/3 multisig, at the end got a pop-up with the wallet output descriptor (wsh) text, and option to save to PDF.

When I tried to import this wsh string into Blue Wallet and then add the seeds, it was fine replacing the 1st xpub with the 1st seed, but the 2nd and 3rd switches reported "fingerprint of new seed doesnt match".

It turned out that in the wsh output string, the 2nd and 3rd cosigner blocks were switched - this was very noticeable from the master fingerprint numbers. The saved PDF had the same issue.

A simple edit to switch the 2nd/3rd cosigner blocks then enabled the wsh string import and xpub/seed swap in Blue Wallet to work.

Subsequent tests on this suggests the wsh string cosigner block output order is entirely random - I've seen 2nd and 3rd swapped, 1st and 3rd swapped - probably with further testing I'd see 1st and 2nd swapped also. Have also seem same for 2/4 multisig, so I assume it's random regardless of combination.

Would be good to have the cosigner block output order in the wsh string in cosigner order 1..n.

**Comment by craigraw** [comment]
> When I tried to import this wsh string into Blue Wallet and then add the seeds, it was fine replacing the 1st xpub with the 1st seed, but the 2nd and 3rd switches reported "fingerprint of new seed doesnt match".

This appears to be a bug in Blue Wallet. The order of xpubs in a multisig should not matter, given that all modern wallets implement BIP67 which sorts keys for each address anyway.

> Would be good to have the cosigner block output order in the wsh string in cosigner order 1..n.

The order of xpubs in a multisig wallet is arbitrary, and will likely differ in a multiparty multisig (since different signers will import their local keys first). Therefore there is no absolute "cosigner order 1..n". It is nevertheless helpful to have some kind of consistent order (for example, to make checking backups easier), so Sparrow sorts the keys when presenting the output descriptor using the same comparator as used in BIP67 to present a canonical output descriptor. See also https://github.com/sparrowwallet/sparrow/issues/985#issuecomment-1578095199
