### ISSUE TITLE
Native Image Camera capture library not loading

### ISSUE THREAD

**Issue by 100millionsat** [sparrowwallet/sparrow#102]
This is actually a different problem - for some reason the native image camera capture library is not being loaded. We should really tackle this in a different issue. Can you provide details of your operating system?

_Originally posted by @craigraw in https://github.com/sparrowwallet/sparrow/issues/87#issuecomment-817625381_

**Comment by 100millionsat** [comment]
windows 10.0.18362 running on a Microsoft surface pro

**Comment by craigraw** [comment]
Thanks for the report - I remember now from the earlier TG query. Reposting the stacktrace here:

![114318166-63e92c00-9ad1-11eb-9ebd-7c09bb389daf](https://user-images.githubusercontent.com/862166/114504470-34503600-9c2f-11eb-9265-aabaff3587f2.png)

This stacktrace is key to understanding the issue better, but it's been cut off on the right - could you supply the full stacktrace?

**Comment by 100millionsat** [comment]
I was concerned about potential privacy concerns with the log file. I replaced my user name with XXXX I think that was the only thing of concern. please let me know if there is anything else that could be used to dox me so I can delete. thanks,
[sparrowlog.txt](https://github.com/sparrowwallet/sparrow/files/6303515/sparrowlog.txt)

**Comment by craigraw** [comment]
Thanks, got it. You can go ahead and delete the log file - sorry I should have been clearer, was only looked for a cut and paste  of that area of the log. Will reply again.

**Comment by craigraw** [comment]
The issue here is that Windows can't load the library at `C:\Users\XXXXX\AppData\Local\Temp\BridJExtractedLibraries16774346556145691140\OpenIMAJGrabber.dll`. Typically this happens because the library was compiled for a different system architecture. That said, the Surface Pro doesn't look unusual. I assume it is running 64 bit Windows? 

Sparrow ships with both Win32 and Win64 versions of the native library. Perhaps it's using the wrong one? Here are the two file sizes to compare your `OpenIMAJGrabber.dll` at the path above against:

- Win32 is 47616 bytes
- Win64 is 57856 bytes

**Comment by 100millionsat** [comment]
nothing is there...
![image](https://user-images.githubusercontent.com/82336277/114637992-3a2a3380-9c90-11eb-9cf1-d4639de92b11.png)

**Comment by craigraw** [comment]
It's in a temporary folder, so it was probably deleted - Sparrow cleans up temporary files when it shuts down.

Can you try again - run Sparrow, try open camera, check in the log for the folder path (it may have changed), look in that folder (without closing Sparrow). You should see `bridj.dll` and `OpenIMAJGrabber.dll` in there.

**Comment by 100millionsat** [comment]
looks like the 64 version which is correct.
![image](https://user-images.githubusercontent.com/82336277/114786332-8a160280-9d43-11eb-91b1-bbe0a4dff983.png)

**Comment by craigraw** [comment]
Ok - further debugging will get a bit technical from here. We need to check why loading that .dll won't work on your system.

To do this, we'll need to use a dependency checker: https://github.com/lucasg/Dependencies

If you can install that software, and try load the `OpenIMAJGrabber.dll` into it, it may provide some clues. We're looking for any errors that might indicate something is missing.

**Comment by 100millionsat** [comment]
I tried to debug this with the dependency checker tonight, but had trouble. I may try again on a weekend when I am not so tired. sorry for the delay. if there is something a little easier I can do in the meantime let me know.

**Comment by craigraw** [comment]
No problem. Thanks for the help in debugging this.

**Comment by craigraw** [comment]
Ok, the solution to this problem is to install two missing Microsoft .dll files. The fix is documented here: https://sparrowwallet.com/docs/faq.html#your-system-is-missing-a-dependency-for-the-webcam

As of 19637fd Sparrow will now display an appropriate error directing users to the link above when this occurs.

Thanks to @kkdao for the help. Closing this off for now.

**Comment by 100millionsat** [comment]
I can confirm this worked. Thank you!!
