### ISSUE TITLE
Feature Request : Shamir Backup SLIP-39

### ISSUE THREAD

**Issue by InfiniteQE** [sparrowwallet/sparrow#103]
Craig would you consider adding SLIP39 support to Sparrow ? As a standard it is far from perfect, bit it has been around since 2019 and has software support in Hermit and hardware support by TrezorT and Cobo.
This would be as an alternative to a standard BIP39 hot wallet, and I appreciate would not add much apart from redundancy for those using hardware wallets to store their private keys.

**Comment by AndreasGassmann** [comment]
I would instead propose integrating [SSKR](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md).

SLIP39 does not support roundtrips with BIP39 seed phrases, meaning that it's not possible to create a sharded backup of an existing BIP39 seed. With SLIP39, users will have to choose what between SLIP39 or BIP39 when generating a new seed, but with SSKR, a seed can be represented in both BIP39 or SSKR format, depending on the users' need.

**Comment by 6102bitcoin** [comment]
Shamir Secret Key Recovery (SSKR) shards can be converted from/to a BIP39 mnemonic. Restoring either the SSKR shards or the BIP39 mnemonic leads to the same HD wallet. The same cannot be said for SLIP39.

Outstanding Action: Research tradeoffs between SSKH vs SLIP39 (I suspect SSKH is preferable) and implement.
Proposed Priority: Low

**Comment by bybv** [comment]
Bump

**Comment by craigraw** [comment]
Support for recovering any arbitrary set of [SLIP39](https://github.com/satoshilabs/slips/blob/master/slip-0039.md) shares has been added in 041b5aa3. The main reason for adding this is due to Trezor [now defaulting](https://content.trezor.io/slip39) to using SLIP39 mnemonics for backups, and recovery of these seeds is now possible in Sparrow. 

It is not possible to convert a SLIP39 share set to a BIP39 mnemonic, so recovered seeds are stored as single SLIP39 shares (using a new randomly selected identifier).

I believe this addresses the original feature request, so closing this off.

<img width="654" alt="Screenshot 2024-08-07 at 14 55 22" src="https://github.com/user-attachments/assets/feba65c9-ee45-4861-8b16-3267a9febf49">
