### ISSUE TITLE
Exception in Application init method

### ISSUE THREAD

**Issue by fanaticalfishing** [sparrowwallet/sparrow#1043]
i am trying to use this, sparrow-server1.7.8-1_arm64.deb, to mix on a  Raspberry Pi 4 Model B Rev 1.1, 4G mem.
I keep getting this error

Exception in Application init method

The desktop version 1.7.8 works fine

**Comment by fanaticalfishing** [comment]
thank you, i will try your suggestons

**Comment by craigraw** [comment]
Can you post the full error (including stacktrace) from sparrow.log in the Sparrow home folder?

**Comment by fanaticalfishing** [comment]
It seems to crash on the start of a mix. I dont have anything to mix right now. when i do, i will try it and post the log here.

**Comment by petzsch** [comment]
Have the same Problem with Ubuntu Server (RPI4) since the last update.
It crashes on new mixes and sometimes in the deposit screen, right after the deposit gets registered and it should create a new address for the next one.

Attached is a stack trace.
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/12241395/sparrow.log)

**Comment by s373nZ** [comment]
I'm having the same issue with Sparrow Server RPI4, but with a different stacktrace, related to Samourai mixing. Log attached, hope it helps.

[sparrow.log](https://github.com/sparrowwallet/sparrow/files/12244630/sparrow.log)

**Comment by craigraw** [comment]
Thanks for the log files. Fixed in 2d7c5dce. The error occurs if a mix happens when the terminal interface is not on the UTXOs screen.

For now, I suggest downgrading to v1.7.7.
