### ISSUE TITLE
Increase Fee (RBF) on a transaction with one output adds new inputs.

### ISSUE THREAD

**Issue by feelancer21** [sparrowwallet/sparrow#1046]
There is a transaction with n inputs and 1 output (no change). I'd like to increase the fees. I'd like to decrease the output about the additional fee amount and keep the current inputs. If I use the RBF feature in sparrow with the slider, sparrow always adds some new inputs to the transaction.

**Comment by thestinger** [comment]
For now, you can manually reduce the amount, remove the added input(s), then send max amount for the UTXOs again. It's a bit painful but I can see why this is happening: it doesn't want to reduce the amount. This always does the wrong thing when using CPFP to speed up an inbound payment since the only output is going to yourself so the amount sent being reduced doesn't matter..

**Comment by craigraw** [comment]
The normal use case is paying an invoice for a fixed amount, where the the payment amount should not be decreased. The additional fee is taken from the change output, but where that is not present or insufficient in value additional inputs must be added.

@feelancer21 can you describe your use case better?

**Comment by craigraw** [comment]
Thanks for describing the use case. I've changed the behaviour in bd1c6c07 to detect when a consolidation transaction is being replaced, and to avoid adding inputs in this situation. The additional fee will be taken from the output. This is actually the same behaviour already used when cancelling a transaction, which is effectively creating a consolidation transaction to replace the original.
