### ISSUE TITLE
Warn when spending in progress mixing utxo

### ISSUE THREAD

**Issue by hium74** [sparrowwallet/sparrow#1049]
Today I tested an account, and I sent it a few sats. Of course, I did not think to use the bad bank, and so, by default, sparrow picked an in-progress mixing utxo to send from.

Before using active mixing utxo, there should be a warning. I would have switched to the bad bank tab to test the account in such a case. 
I guess now my mix for that utxo is irreversibly broken, isn't it?

**Comment by RequestPrivacy** [comment]
I'm not sure if this would be a great addition. Postmix is there to be spend. Such a warning could discourage people to use their coins (and e.g. use unmixed coins and "save" their "precious" mixing ones). 

For your testing case I agree, it was an unfortunate event...still, I don't feel strongly about  a default warning if a mixing utxo is spend.

**Comment by hium74** [comment]
I really don’t see the case of an in progress mixing that somebody, after
having spent money for it, wants to interrupt.

The warning is not for all utxo but only for the one with coinjoin in
progress. It could be also an option. I keep thinking it would be very
useful. But of course, that is just my point of view

**Comment by hium74** [comment]
Besides, I wasted about 15 dollars of fees because of it. So, you argument
about not spending money results to be pretty weak, at in my opinion

**Comment by RequestPrivacy** [comment]
>The warning is not for all utxo but only for the one with coinjoin inprogress.

Since all utxo's in postmix already paid their fee and can remix freely I don't get the differentiation between utxo sitting idle and waiting to get re-selected?

> I keep thinking it would be very useful. But of course, that is just my point of view

So you mean every time YOU, the user, tries to spend from postmix (by going specifically into that account) there should be a warning? That would be like your email client warning you that your email will be send after you hit "Send". 

Don't get me wrong, but as a user of Sparrow that will annoy the heck out of me. But that's also just my opinion on this matter and please, don't mistake my opinion for the one of the project - just because I answered first.

Maybe craig can make it so that a user can opt-in to such a warning. 

---

> Besides, I wasted about 15 dollars of fees because of it.

No, you wasted $15 because of this:
> I did not think

**Comment by hium74** [comment]
From your answer, you clearly did not get the problem; undoubtedly, my bad
English.

Let’s put it this way, if you are mixing an utxo, will you ever want to
spend it a bit after having paid Whirlpool, or is it more likely that you
want to finish the process?

I currently have an utxo of about 4,980,000 sats which are unusable for
further mixing (unless I pay whirlpool again creating smaller utxo which I
don’t want.
Not sure. Is it something you would enjoy happening?

If I may, these are exactly the barriers that Btc community has to resolve.
Btc is extremely difficult, does not really need more criticality's if you
care about adoption.

It can be a simple preference. You will discovered it will be set on most
computer.

Anyway, I really appreciate your will to discuss issues regardless you
agree.
👍🏻

**Comment by RequestPrivacy** [comment]
I think I got you the first time but as a sanity check for me: 
1. You send the coin(s) through whirlpool
2. They did their first mix completely
3.  They where remixing
4. You wanted to try an account (of a different wallet) by sending out from your Sparrow wallet
5. You where in the Sparrow Postmix account for sending

And you wondered why Sparrow picked a mixing utxo resulting in an no-pool-denomination-sized-utxo which broke the equal output denomination and it therefore stopped remixing???

> Is it something you would enjoy happening?

No, of course not. But I try to be 10 steps ahead when dealing with Bitcoin and always question what I do, what the wallet (might) do and double checking everything.

> It can be a simple preference. 

Yeah but the warning would need to be opt-out since it would need to be shown at the beginning to be effective (e.g. for something like you experienced). Maybe something which encourages spending but also explains with the option to directly turn it off. Something along the lines of:

"_You're about to spend the first time from Postmix. Spending from this account is very privacy preserving and is therefore encouraged. It will use some of your whirlpooled UTXOs though, which means that any potential change isn't eligible for free re-mixing anymore since it looses its equal output amount._"
With a selection if the warning should be also displayed the next time.

**Comment by hium74** [comment]
No, the problem is not about spending from post mixes. I was NOT in the
post mix tab. I was in the main deposit, then why it chose a whirlpool utxo
while there were sufficient funds in the bad bank???

You might be 100 steps ahead, people is very scared about this stuff, very.
And let me tell you, I don't think choosing from money mixing in place of
free SATs standing in bad bank is good programming.

I'm into music, I would not talk to you about half dimished scale with zero
possibility to be understood. coders should always have close to them
someone who doesn't understand coding, because you give for granted stuff
that is not

**Comment by craigraw** [comment]
>  I was in the main deposit, then why it chose a whirlpool utxo while there were sufficient funds in the bad bank???

Sparrow will definitely **not** use a Postmix UTXO (or for that matter a Bad Bank one) when you are spending from the Deposit account. I believe you are mistaken.

> I don't think choosing from money mixing in place of free SATs standing in bad bank is good programming.

The privacy implications of spending from each wallet (Deposit, Postmix, Bad Bank) are quite different. This is why Sparrow does not pick UTXOs from other accounts when spending.

> Before using active mixing utxo, there should be a warning.

If you are spending from the Postmix account (which I believe you were in this case) then spending a UTXO that is currently registered for mixing is of no consequence. The Whirlpool client will simply immediately pick another one, as it does every hour anyway. Postmix is for spending!

**Comment by RequestPrivacy** [comment]
I'm not a dev so maybe there is a bug, but I can't spend from the Deposit account if there are not utxo's in it (while there are in others). That'd be a serious flaw and isn't reported by somebody other than you, so maybe you have mixed up the accounts?

**Comment by hium74** [comment]
I will make a simulation of the situation as described by me tomorrow (now
it's late) and let you know it

**Comment by hium74** [comment]
Hello,

So you were right (although partially in my opinion); luckily is not
possible to spend from the main deposit any amount from the post mixes tab.
So it was my mistake. Even so, you might wonder why I already made three
bad mistakes in your guy.
I've been dealing with Bitcoin, with hundreds of transactions and all kinds
of HW, for over three years, and the only mistake happened inside the
Sparrow wallet. I love sparrow wallet. This is the reason I adopted it.

My mistake, in fact, means that certain aspects still need to be improved.

1 - Even when a user is in the post mix tab should be warned when sending a
utxo that is processing under Whirlpool, as it is clearly undesirable, or I
might say unwanted, in most conditions. Honestly, your analogy with email
doesn't seem to fit much for me. A more related metaphor would be sending a
bank wire from a bank account that takes you on a negative balance. You
might want to get warned about your balance in such a situation, but you
don't want it if you stay positive.

2 - The layout of the guy is done so that such mistakes can quickly happen.
Position, dimensions, colors, and characters may help better understand
your location. I love the graphic but cannot favor it over safety.

Please consider my issues.

Best Regards

**Comment by RequestPrivacy** [comment]
> I've been dealing with Bitcoin, with hundreds of transactions and all kinds
of HW, for over three years, and the only mistake happened inside the
Sparrow wallet.

Yeah but Whirlpool seems to be pretty new to you so check out the [docs](https://www.sparrowwallet.com/docs/mixing-whirlpool.html) or this [article](https://blog.samourai.is/diving-head-first-into-whirlpool-anonymity-sets/)  if you haven't already.

> 1 - Even when a user is in the post mix tab should be warned when sending a
utxo that is processing under Whirlpool, as it is clearly undesirable, or I
might say unwanted, in most conditions.

For what purpose do you mix your coins if not to protect your privacy while SPENDING from postmix? Spending from postmix is not "undesirable" or "unwanted", it is recommended. The only time you should really use unmixed funds is for a self transfer or a transfer where you're comfortable with the counterparty to see your previous utxo balance/history. So your proposed "improvement" is - at least for me - an actual step back, encouraging users to horde their "good" coins and spend their "bad" ones (i.e. the unmixed).

What you should do is to pick multiple pool denominations so that one smaller spend doesn't destroy a "too large" mixing utxo.

> 2 - The layout of the guy is done so that such mistakes can quickly happen.
Position, dimensions, colors, and characters may help better understand
your location. I love the graphic but cannot favor it over safety.

First, if you value safety, spend from postmix. 
Second, a user has to actively click on the postmix tab to spend from there. 
Third, the transaction consists only from pool sized denominations, so it is pretty obvious that you spend from postmix. 

I could go on with other hints (or "warning signs" if spoken from your reference view) that you're about to spend from postmix. So excuse my bluntness, but for me the only thing that needs improvement is your carefulness while handling Bitcoin. It seems you rush things, but again...just an opinion you haven't really asked for.

That being said, as a musician you seem to have a creative mind. I guess craig is always open for concrete solutions so feel free to make screenshots and open your favorite image editor to design a "better" way of layout.

**Comment by hium74** [comment]
Not sure who I am talking to now. It is pretty weird not to know your
interlocutor's name.

Anyway, I discovered from your email that utxo that maybe have only pasted
the premix is good to spend—new knowledge.

I'm a musician, not a graphic; I'm terrible at visuals. And your
juxtaposition is out of sense.

So I will end up here; good luck with spending your premixed, not postmixed
UTXO! I hope you won’t give such advice to people

Bye for now
