### ISSUE TITLE
Fee rate changes (lowers) after signing

### ISSUE THREAD

**Issue by keblek** [sparrowwallet/sparrow#105]
I think its because the fee rate doesn't count the bytes of the signature that get added. 

It goes from 25.27 to 30.78 to 25.23 sats/vByte. 

I'm kinda confused by why the rate changes.

I've attached pictures to show what I mean.

![sparrow-send](https://user-images.githubusercontent.com/68111648/114941751-d6486c00-9e43-11eb-9b77-56c9d00e7490.png)
![sparrow-txview](https://user-images.githubusercontent.com/68111648/114941756-d6e10280-9e43-11eb-9088-c0f73d0699be.png)
![sparrow-finaltx](https://user-images.githubusercontent.com/68111648/114941747-d47ea880-9e43-11eb-9649-a73d2a683518.png)

**Comment by craigraw** [comment]
This is a good question, even though Sparrow is functioning correctly :)

The reason the fee rate changes is because we can't know the length of the signatures exactly, before the transaction has actually been signed. This means the first rate (25.27) is an estimate using dummy signatures. The second rate (30.78, in the light grey color to indicate it is not final) is the rate without the signatures, since they haven't been added to the transction yet. The third rate (25.23) is the rate with the actual signatures, so we know the estimate here was pretty good.

**Comment by keblek** [comment]
That's what I thought! Thanks for the explanation.

Would it be possible to add a `~` or `approximate rate` or some other symbol in that view to show that it's an estimate of what you plan to spend? I did not pick up on the shading, it might be too subtle.

**Comment by craigraw** [comment]
Makes sense, I've had queries on this before. Added a "(non-final)" suffix to the field when the tx has no signatures in f8023e9.
