### ISSUE TITLE
Unable to Sign Message with Singlesig Address and BitBox02

### ISSUE THREAD

**Issue by swiss-chris** [sparrowwallet/sparrow#1067]
Today I tried signing a message with BitBox02 and Sparrow version 1.7.8

The window where I could paste the address and message only said "Verify" and the sign button was greyed out.

I made sure that the hardware wallet was connected and recognized by Sparrow, by displaying the receive address on the device with Sparrow.

When I tried signing with Electrum, it worked without any issues.

Anything I can do in the future to get this to work ?

**Comment by craigraw** [comment]
Did you paste in an address from a wallet that you imported from the Bitbox02? If not, create a new wallet and import the BB02 using the Connected Hardware Wallet button.

Re signing a message, here's another way to do it: Go to the Addresses tab, click on an address and right click for the context menu. Select Sign/Verify message and the address field will be filled with that address.

Either way you do, I've tested with the Bitbox02 on this side and message signing works fine, so long as Sparrow knows that the wallet was imported from the BB02. Note that due to path restrictions the Bitbox02 only supports signing on mainnet.

**Comment by swiss-chris** [comment]
I had it set up as a watch only wallet, because I have 2 hardware wallets I use with the same Sparrow Wallet (both containing the same key). After (re-) importing my bitbox into the same wallet, all the steps worked like you said. Thanks for clarifying.
