### ISSUE TITLE
[Feature Request] Summary View for multiple open wallets

### ISSUE THREAD

**Issue by mariusb** [sparrowwallet/sparrow#1086]
I like the new summary view for a single selected wallet.
It would be great if there was a combined summary view of all open wallets so that one can see a global view.

**Comment by marcocattaneogotam** [comment]
Yeah +1

**Comment by RequestPrivacy** [comment]
>  ...if there was a combined summary view of all open wallets so that one can see a global view.

Imho it would be good to let the user decide if he really wants to have an overview over all OPEN wallets, only SPECIFIC ones that are open or maybe even some kind of template builder where he can add wallets that will be opened (if they aren't yet)  once he opens the template summary.

I'm thinking of a couple of cold wallets that I can add to a template/group-summary e.g. named "Coldstorage" so that once I open the summary "Coldstorage" all wallets that have been added will open so that I can check whether nothing has changed.

**Comment by InnocuousFinch** [comment]
Add this to the list of people asking for this feature: #1370

**Comment by craigraw** [comment]
Added in a167f6ae. There is now a 'Show All Wallets Summary' menu item in the View menu. The display is similar to the current Show Wallet Summary dialog, but with a root item showing the total balance of all open and unlocked wallets. The balance chart similarly shows a composite view of the balances of all wallets over time.
