### ISSUE TITLE
Unconfirmed after CoinJoin

### ISSUE THREAD

**Issue by zn9n9bhg** [sparrowwallet/sparrow#1092]
After a few mixes one of the transactions got stuck, been 4 days. See https://mempool.space/tx/c8ceb4907c0ede702b608df8ea5ff1229b19a0d480f149a6b5d2b70d030bbe2c

What are my options? Can/should I just try to send the Postmix UTXO to another wallet? If I wait it out and If the transactions gets pruned from mempool does that mean sparrow steals my 100,000 sats?

How can I prevent this in the future?

**Comment by RequestPrivacy** [comment]
This is somewhat normal. The transaction fee was only 10.3sat/vbyte and as you can see, the transactions that got confirmed in the last blocks have a fee way above that. So you need to wait until it gets confirmed. 

Don't worry, nothing can be stolen. You always have custody over your coins with whirpool. So either the transaction gets confirmed or it doesn't. But the coins remain always in your wallet, even if the transaction is "purged" from every mempool.

> How can I prevent this in the future?

It depends. If you're remixing (as you indicated if I read the "After a few mixes" correct) there isn't something you can do about it. New entrants choose the transaction fee for the whole mix. If they choose a rather low fee and there is a spike in the fee environment shortly thereafter, the complete mix might end in the situation you're currently in - they need to wait for the confirmation.

**Comment by zn9n9bhg** [comment]
> But the coins remain always in your wallet, even if the transaction is "purged" from every mempool.

This is good to hear, I wasn't sure since I didn't manually send the transaction.

> New entrants choose the transaction fee for the whole mix

I understand, but I am not a fan of being at the whim of my funds being locked up for a period of time all because some person wanted to save 25 cents. Is it possible to only be involved in mixes which have a fee that is less likely to get stuck? I am wary of repeat mixing now, especially if I was to mix more than 100k sats. Please consider a feature where we can have more control over who we are mixed with in terms of fees

**Comment by RequestPrivacy** [comment]
> Please consider a feature where we can have more control over who we are mixed with in terms of fees

Whirlpool has been developed by Samourai Wallet and Sparrow incorporated it into its wallet. So an unilateral change of the workings isn't feasible as it would break comparability. 

> I understand, but I am not a fan of being at the whim of my funds being locked up for a period of time all because some person wanted to save 25 cents.

IIRC the fees for new entrants are calculated as the mean of the last 10 blocks or something like that. So if a high fee environment is encountered the coordinator increases the fee after said time so that even "greedy" (i.e. low transaction fee) entrants have to pay a pretty high fee so that mixes get confirmed rather fast.

But if fees increase rapidly some small number of mixes might get stuck as they still have been constructed with the rather low fee. 

If you think about it, there isn't much one can do otherwise: you would need to know the future or raise the fees all the time to such an insane amount that they ALWAYS get confirmed immediatly. But then users would complain that they pay a fee of like $5 if $0.10 would suffice.

How would you add more fees to the transaction but making sure that there are (a) still only 5 utxos with the same denomination as output and (b) you use utxos which haven't been seen together with the utxo that already participates in the mix?

**Comment by RequestPrivacy** [comment]
As I can see your mix has been one of the newer surge cycles, as there are 7 equal outputs, not 5 like the default. For explanation of surge cycles see [https://blog.samourai.is/introducing-whirlpool-surge-cycles/](https://blog.samourai.is/introducing-whirlpool-surge-cycles/), it's a newer feature of whirlpool.

**Comment by zn9n9bhg** [comment]
Luckily someone used CPFP to help it confirm. How would I do a CPFP  from sparrow in the future if this happens?

**Comment by craigraw** [comment]
It looks like the CPFP was actually a consolidation - normally you would not do this with Whirlpool UTXOs to avoid indicating common ownership. 

To CPFP an unconfirmed transaction in Sparrow, right click on the Unconfirmed cell in the table.
