### ISSUE TITLE
Trezor One- Connection Issue

### ISSUE THREAD

**Issue by java4tech** [sparrowwallet/sparrow#11]
I'm testing Trezor-One on windows, 
1. Connection seemed to be unstable. It takes a while to even show up. If this is just an implementation issue then may be we can have a UI/UX changes to keep user's engaging otherwise it looks like nothing is happening.
2. Pin entry is also unstable, Pin grid on hardware wallet disappears withing few seconds( Even before completing grid on the PC). I had to try multiple times to get it working. 

In general response time is very slow Tested Only On Windows 10

**Comment by craigraw** [comment]
That's odd - Trezor One is one of the most heavily tested HWWs, and I can't reproduce this on Windows 10. Response times are reasonably fast - around 1 to 2s. 

Regarding the pin entry issue, it's possible this is caused by the background scanning for new HWWs which Sparrow performs to keep the current set of connected HWWs up to date. Unfortunately, if there is a pin entry screen on the Trezor when this is done, it disappears. Sparrow checks and avoids background scanning in this case, but it may have happened anyway. Any chance there was another instance of Sparrow running at the time (or possibly other wallet software)?

To check response time, if possible download [HWI](https://github.com/bitcoin-core/HWI/releases/tag/1.1.2) and try to see if the response times are poor running `hwi.exe enumerate`. They should be reasonably quick (1 - 2s).

**Comment by java4tech** [comment]
I have tried your recommendations and also remove trezor bridge just to make sure there is no conflict, but still same issue. Its taking 10 - 30 seconds in some cases. Trezor works fine in the browser though. That means it is unrelated to this project, So I'm going to close issue here.
