### ISSUE TITLE
Password Requirement

### ISSUE THREAD

**Issue by junnie082** [sparrowwallet/sparrow#1121]
Hello!!
I have some questions creating new account.
What are the illegal characters when creating passwords? Are all the characters that exist in this world available? Even the emoticons?
Also, are there any limits on lengths in passwords?

**Comment by rapidlab309** [comment]
No restrictions. Could be anything, including emojis and in any length.
Take into consideration that it should be complex, but not over the head in the way that would require you to deal with it. Sparrow's encryption algorithm prevent it from being brute forced ([Argon2](https://github.com/P-H-C/phc-winner-argon2)).

"Sparrow is desktop focussed and uses a configuration of [Argon2](https://github.com/P-H-C/phc-winner-argon2) (winner of the Password Hashing Competition in 2015) configured to take at least 500ms on modern hardware to derive the key from your password in order to unlock your wallet."

**Comment by craigraw** [comment]
All UTF8 characters are permissible, there are no restrictions in length.
