### ISSUE TITLE
Feature Request: Text Search within Labels

### ISSUE THREAD

**Issue by statusquont** [sparrowwallet/sparrow#1124]
I envision the ability to double-click the Label column header to turn it into a text field that I could then type into. As I type it would filter the rows to only show rows who's label contained text that matched the entered text string. If I had a bunch of UTXOs that labeled in a particular way I could then use this feature to find them all, select them all, and consolidate them. 

A more advanced future version might allow for more complex searches like wildcards characters or even regex.

**Comment by craigraw** [comment]
There is already column sort functionality attached to the Label column header, which is the standard and expected behaviour. The Search Wallet function (also available via shortcut) provides label search functionality.

Given this, I'm not inclined to make the Label column header non-standard in behaviour.
