### ISSUE TITLE
Making UTXO selection tab more intuitive

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#115]
checkbox to select 🔳  like wasabi does,  CTRL+click is not that common knowledge.
Electrum has click+drag and drop feature to select items.

![image](https://user-images.githubusercontent.com/388716/116772978-a17e0c80-aa20-11eb-89ff-14ba0f99866f.png)

Clearer wording, "Select Coins to spend"

The histogram of UTXO currently takes a lot of space for how useful it is, when showing only 7 UTXO

There's a bug where selecting all but one UTXO does not include Other.

Seeing which coins are unconfirmed or have unconfirmed parents is very useful.
(currently showing block-height = 0 for unconfirmed,  -1 or -2 ect for those with unconfirmed parents)

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/116773368-06d2fd00-aa23-11eb-89f1-91a69b3a15ce.png)

Wallet is tall so there's often a lot of space to get lost looking for important buttons.

**Comment by craigraw** [comment]
> checkbox to select 🔳 like wasabi does, CTRL+click is not that common knowledge.

I'm still open to this, but I'm not convinced it's necessary. Ctrl/Cmd + Click is pretty well known by now (it's impossible to properly use any operating system file explorer without it) and most people doing coin selection will find it quickly enough. Adding a checkbox column reduces space for the other columns.

> Clearer wording, "Select Coins to spend"

I'm not sure it improves much on the current label?

> The histogram of UTXO currently takes a lot of space for how useful it is, when showing only 7 UTXO

Can now be hidden via the View menu.

> There's a bug where selecting all but one UTXO does not include Other.

Fixed in adcddfa.

> Seeing which coins are unconfirmed or have unconfirmed parents is very useful.

The UTXO table will now indicate whether the UTXO has unconfirmed parents.

**Comment by craigraw** [comment]
> Wallet is tall so there's often a lot of space to get lost looking for important buttons.

Perhaps, but there are significant advantages to keeping the actions buttons in the same (and expected) placement at the bottom of the form (where the eye naturally travels as the elements above are filled). There is an argument for having the Clear button next to the Max button, but there is perhaps a better argument for having it below in that it resets the whole screen, not just the UTXO selection.

**Comment by 6102bitcoin** [comment]
Outstanding Action: Make ability to select multiple UTXO's more obvious in the UI.
Proposed Priority: Low

**Comment by craigraw** [comment]
I think more feedback is required here - I believe adding checkboxes (which then create three different states rather than two - selected/unselected/checked) could actually make the UI worse. I'm not convinced there is an issue here - this is the only time it's been raised that I'm aware. I'm going to close this off, please add feedback below if you think it should be reopened.

**Comment by 6102bitcoin** [comment]
I think some indication that multiple utxo's can be selected would be beneficial, even if it is just a note.

**Comment by craigraw** [comment]
Added a tooltip to the 'Send Selected' button:

<img width="418" alt="Screenshot 2021-05-24 at 09 37 27" src="https://user-images.githubusercontent.com/862166/119313962-72039e00-bc74-11eb-9677-654c4b2be6d9.png">
