### ISSUE TITLE
Randomize version nr of transactions

### ISSUE THREAD

**Issue by checkuon** [sparrowwallet/sparrow#1178]
It is already possible to change the header version nr when reviewing a transaction before broadcast. Would be interesting to either have this randomize by default, or have an option to in settings that enables this. Makes tracing transaction a little bit more difficult.

**Comment by craigraw** [comment]
Changing the transaction version randomly would affect the interpretation of sequence numbers, which would potentially be confusing. I haven't managed to find a chart of transactions against their version numbers - it would be interesting to see which anonset is larger. I think I prefer standardisation of version 2 rather than keeping version 1 alive.

**Comment by checkuon** [comment]
> the interpretation of sequence numbers

I do not understand what that means. In any case, looks like version 2 is winning out: https://transactionfee.info/charts/transaction-versions/

**Comment by craigraw** [comment]
See BIP68 (or https://bitcoin.stackexchange.com/questions/51394/what-is-version-used-for-in-bitcoin-transactions-does-it-have-any-meaning).

Closing this off.
