### ISSUE TITLE
Error importing from Specter 1.14.5

### ISSUE THREAD

**Issue by shawnyeager** [sparrowwallet/sparrow#1197]
I successfully imported several other wallets from Specter exports, however, one produces the following error on multiple attempts to import to Sparrow 1.8.1 (path redacted):

`Imported Specter Desktop wallet was invalid: Keystore coldcard derivation
of XXXXXX' in P2WPKH wallet matches another default script type.`

**Comment by craigraw** [comment]
You can disable derivation path validation in the General Preferences.

**Comment by craigraw** [comment]
Yes, this friction is intentional. Reusing a derivation path means reusing keys, which means a loss of privacy. Even though you may have two wallets with different script types, they will be linked on the blockchain if using the same derivation path. There are good reasons why different script types have different derivation paths.
