### ISSUE TITLE
[Feature] BIP 351 private payments

### ISSUE THREAD

**Issue by Scalena** [sparrowwallet/sparrow#1200]
[BIP 351](https://github.com/bitcoin/bips/blob/master/bip-0351.mediawiki) is a new private payment scheme which can be viewed as essentially an improved version of BIP 47. Its support would be a great feature for a privacy-focused wallet.

**Comment by craigraw** [comment]
BIP351 is not "essentially an improved version of BIP 47" since it does not support light clients, but requires scanning of the blockchain, and therefore access to all blocks. While this is possible with Sparrow connected directly to Bitcoin Core, it is not  possible with connections to Electrum servers. More generally, I believe until this limitation is solved neither this BIP, nor Silent Payments, will see significant adoption. Put another way, all schemes of this nature make certain tradeoffs - I regard the tradeoffs that BIP47 has made as more practical to date.
