### ISSUE TITLE
Confusing usage of the word "keystore" 

### ISSUE THREAD

**Issue by laurent1983** [sparrowwallet/sparrow#1206]
While I was connected to my hardware wallet I had this screen :

![photo_2023-12-25_11-43-47](https://github.com/sparrowwallet/sparrow/assets/17447756/00b70301-c0c0-4eb4-ba19-0aee93b93119)

I was confused about the word "keystore" so i googled it : 

![photo_2023-12-25_11-43-51](https://github.com/sparrowwallet/sparrow/assets/17447756/5e844c7e-d512-4fcc-b7a9-152a16e30a0f)

Of course, I got scared since the last thing I wanted is an encrypted version of my private keys on my computer. If one buy an hardware wallet, is to avoid that in a first place.

It seems that I am not the only one to get confused. 

![photo_2023-12-25_11-43-56](https://github.com/sparrowwallet/sparrow/assets/17447756/74dd4952-1178-4086-aa30-696cdd6dc35e)
![photo_2023-12-25_11-43-57](https://github.com/sparrowwallet/sparrow/assets/17447756/276795e2-605c-4d0a-a23d-281a52686614)

Right now, I'm still not sure about what that keystore is exactly. Does it extract the private keys in an encrypted version or not?

If yes, users should be aware of it.

if not, users should be aware of the exact meaning of keystore. What is the difference between a keystore and a xpub and why do we need this to send/receive BTC with the hardware wallet?

**Comment by craigraw** [comment]
> Right now, I'm still not sure about what that keystore is exactly. Does it extract the private keys in an encrypted version or not?

It does not. You can ignore the Google answer about Ethereum.

> if not, users should be aware of the exact meaning of keystore.

A keystore is simply a term that indicates a store of keys - public or private. In this case, because you are importing a hardware wallet, it will only ever contain public keys. However, if you were to create a keystore with BIP39 seed words, it would contain private keys. There is nothing particularly special about the word keystore - you could also use the word wallet, but that would become confusing in a multisig (wallet compromised of wallets).
