### ISSUE TITLE
Sparrow as a service on Start9 Server

### ISSUE THREAD

**Issue by marc3linho** [sparrowwallet/sparrow#1240]
I have seen that this request has already been made to bring Sparrow as a service on a Start9 Server - https://github.com/sparrowwallet/sparrow/issues/969 .
I also found posts on this issue in the Start9 Community Forum - https://community.start9.com/t/sparrow-as-a-service/345/5
Here is a quote from the forum "Check out the Developer Docs 3 for more info. If **Craig** is interested, we’d love to help get this running and published to our Marketplace such that users can get one-click access to it."

@craigraw it looks like it would be a lot more work to get Sparrow running on a Start9 server. But it looks like the start9 guys are interested to help with it.

**Comment by craigraw** [comment]
I appreciate the sentiment, but I'm not sure how Sparrow Desktop could become available via "one-click access" as it is a native application. Specter can offer this because it is a browser-based wallet, but that comes with it's own issues. Sparrow Server is also a native application, and while that can run on a Start9 server, the terminal interface is not a natural fit for the Start9 UI.

Happy to reopen this if I've missed something.
