### ISSUE TITLE
Privacy mode?

### ISSUE THREAD

**Issue by jbnation** [sparrowwallet/sparrow#1255]
I can click on the amount and change it from BTC to sats.  I was wondering if a feature could be added that would allow all of the amounts to go to *****.   I don't know how easy or hard something like this would be to implement but it seems that it could be useful.

**Comment by rapidlab309** [comment]
Could you share any situation this would be needed? Like, `Ctrl/CMD + L` will do much more than just hide balance & amounts.

**Comment by jbnation** [comment]
I wanted to show some friends of mine how to use sparrow wallet but I didn't want to expose what I had.  I could create a wallet with nothing in it but then you don't have access to all the tabs to show what they do.  I could just create a wallet and put a small amount of funds in there to show them its functionality but I didn't really have time to do that and really didn't want to send small amounts with transaction fees being what they were.  Then I remembered how some other wallets allow you to tap on the amount you have and then it hides the value.  It's probably not worth doing since there probably isn't a great need for it but I was just curious and thought I'd throw it out there.  I ended up just sending them some YouTube videos to watch.

**Comment by craigraw** [comment]
Using testnet is really the better answer here. You can restart Sparrow in testnet using the Tools menu, and then get some coins from a bitcoin testnet faucet (or ask on the Sparrow Wallet TG group). This allows you to demonstrate using Bitcoin without needing to hide amounts (or pay fees that cost real money), since the coins have no value.
