### ISSUE TITLE
wait to send low fee transactions until they will be accepted by the electrum server

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1264]
In https://github.com/sparrowwallet/sparrow/issues/847 I was asking for a way to manually rebroadcast transactions that _were accepted_ by the electrum server you are connected to, but then is _later pushed out_ of the electrum server's mempool. When that happens you don't know if all the other nodes have also forgot about the transaction and the transaction may never get confirmed (even if fee market dynamics change and fee rate of the transaction later becomes high enough).

The issue was closed because it seems as though even if just a few nodes out there have a huge mempool, you might be okay and the transaction may eventually reach a block. I'm not sure if that will always be the case, so https://github.com/sparrowwallet/sparrow/issues/847 may need to be reopened in the future.

Another scenario is you want to broadcast a transaction with a fee rate that is much lower than what will be accepted into the mempool of the electrum server that you are connected to. The most obvious scenario is moving funds in and out of cold storage where you have a low time preference for processing and a high fee preference (wanting a low fee).

Currently, if the transaction you are trying to submit won't fit in the mempool, Sparrow Wallet will give you an obscure error (and you need to look at the log files to see why the electrum server is rejecting the message). Then you need to completely start your transaction over and try to increase the fee and sign a new transaction. Or, you need to wait and manually rebroadcast that raw transaction some other way.

I think Sparrow Wallet should properly check to see if the transaction is going to fit in the mempool of the electrum server, and if it won't, rather than trying and failing, let the user know that it won't be accepted right now. Then, give them two options:

1. Don't let them broadcast the signed transaction right now, tell them they need to wait for fees to drop before they can try to broadcast.
2. Schedule the signed transaction for broadcast when fees drop, telling them they need to leave Sparrow Wallet open for this to be possible.

At the very minimum, it would be nice when creating an unsigned transaction to make it more explicit when selecting the fee that the fee they are choosing will be rejected by the server. Right now, if you put it below "try then replace" it says "below minimum". I think the "below minimum" message should be changed to something that is more clear like "your electrum server will not accept this transaction".

There is some related discussion in https://github.com/romanz/electrs/issues/397 about having the electrum server do the scheduling. I think that both a wallet and electrum server based solution are going to be best in order to address all types of users because there will be some people using private and some people using public electrum servers.

**Comment by craigraw** [comment]
> Then you need to completely start your transaction over and try to increase the fee and sign a new transaction.

Not true, you can just go back to the Send tab and adjust the fee. Obviously you will need to resign as it is now a different transaction.

> Sparrow Wallet will give you an obscure error (and you need to look at the log files to see why the electrum server is rejecting the message)

I specifically do not show the obscure error returned by Bitcoin Core (or indeed any message from the connected server) since that has been proven to be a way to fool and defraud users. You may wish to look into the "Electrum 4" debacle, which was specifically caused by leveraging this attack vector.

That said, I've made a fair bit of progress in decoding the cryptic Bitcoin Core errors and presenting them nicely (in my own language) in recent versions, especially when it comes to insufficient fees.

> Right now, if you put it below "try then replace" it says "below minimum".

Unfortunately the current purge rate is not provided by the Electrum server. It is only provided at this time if you configure mempool.space as your fee rate provider. In other words, this data cannot be generally relied upon to be present. In addition, if you are connected via Tor, Sparrow will broadcast using a random external service over Tor (like blockstream or mempool.space) resulting in a successful broadcast since the mempool there is unconstrained. 

> Don't let them broadcast the signed transaction right now, tell them they need to wait for fees to drop before they can try to broadcast.

This is what Sparrow already does:

<img width="472" alt="Screenshot 2024-02-12 at 17 25 26" src="https://github.com/sparrowwallet/sparrow/assets/862166/28443c4a-1bb0-4df1-aef5-1e97b91fec92">

> Schedule the signed transaction for broadcast when fees drop, telling them they need to leave Sparrow Wallet open for this to be possible.

With the exception of Whirlpool (which is why I wrote Sparrow Terminal), I do not believe it is a good idea to encourage users to leave Sparrow open for long periods. Sparrow is a client, not a server, and leaning too far into "always on" requirements may lead to undesirable outcomes, like transactions unexpectedly not getting broadcast. As you suggest, it is better for the server to handle these kind of requirements from an engineering perspective. Unfortunately, there is no support for this right now in the Electrum protocol, which is where this feature would need to start imo.

**Comment by AndySchroder** [comment]
> > Right now, if you put it below "try then replace" it says "below minimum".
> 
> Unfortunately the current purge rate is not provided by the Electrum server. It is only provided at this time if you configure mempool.space as your fee rate provider. In other words, this data cannot be generally relied upon to be present. In addition, if you are connected via Tor, Sparrow will broadcast using a random external service over Tor (like blockstream or mempool.space) resulting in a successful broadcast since the mempool there is unconstrained.

How do you determine the "below minimum" fees with the slider then? That never comes up if not using mempool.space for fees?

**Comment by craigraw** [comment]
> That never comes up if not using mempool.space for fees?

Correct. Trying setting your Fee rates source to Server in the Preferences.

**Comment by AndySchroder** [comment]
Interesting, that is a subtle difference between using mempool.space and a private electrum server!

Where do you suggest we request the electrum protocol add support a mempoolminfee? Should an implementation such as electrs be approached and get one implementation supporting it first before trying to get that into the electrum standard?

What happens if you use the Cormorant mode with bitcoin core? https://bitcoincore.org/en/doc/26.0.0/rpc/blockchain/getmempoolinfo/ has a mempoolminfee field that it returns. I don't have a full mempool right now, so I can't test it.

**Comment by AndySchroder** [comment]
I confirmed that newer versions of Sparrow give a clearer error message now, but what I'm getting doesn't show the "increase the fee to at least 907 sats to try again" part. What scenario is required to get this level of detail?

**Comment by AndySchroder** [comment]
> With the exception of Whirlpool (which is why I wrote Sparrow Terminal), I do not believe it is a good idea to encourage users to leave Sparrow open for long periods. Sparrow is a client, not a server, and leaning too far into "always on" requirements may lead to undesirable outcomes, like transactions unexpectedly not getting broadcast. As you suggest, it is better for the server to handle these kind of requirements from an engineering perspective. Unfortunately, there is no support for this right now in the Electrum protocol, which is where this feature would need to start imo.

Okay, so you are basically suggesting that this issue should be closed then in favor of https://github.com/romanz/electrs/issues/397 ?

For public electrum servers, I'm not sure what a sustainable solution might be. I think in the future maybe there is going to need to be a way to pay an electrum node to hold onto your transaction and re-broadcast it, vaguely "similar" to how watchtowers work in lightning. I guess possibly we are going to need to pay all public electrum nodes in the future for all access since it won't be sustainable to have all volunteer electrum nodes, so maybe the problem is more general. I don't think we can rely on "using a random external service over Tor (like blockstream or mempool.space) resulting in a successful broadcast since the mempool there is unconstrained" forever.

**Comment by craigraw** [comment]
> Where do you suggest we request the electrum protocol add support a mempoolminfee? Should an implementation such as electrs be approached and get one implementation supporting it first before trying to get that into the electrum standard?

It's unclear to me, although I will say that https://electrumx-spesmilo.readthedocs.io/en/latest/protocol.html (owned by the Electrum wallet devs, the original inventors of the protocol) is for me the definitive specification. But implementations have added their own extensions to it over the years. I believe that a popular extension (like rebroadcasting) built into one implementation would be copied by the others. 

> What happens if you use the Cormorant mode with bitcoin core?

Sparrow currently doesn't look for this information from the connected server (as there is no Electrum protocol call for it), but rather the fee rates source, so it doesn't matter.

> I confirmed that newer versions of Sparrow give a clearer error message now, but what I'm getting doesn't show the "increase the fee to at least 907 sats to try again" part. What scenario is required to get this level of detail? Is that for Cormorant mode with bitcoin core and not electrum?

Depends on the situation, and since the error message is ultimately coming from Bitcoin Core it doesn't matter whether Cormorant is used or not. As to what error messages Sparrow gets, [it's a bit messy](https://github.com/sparrowwallet/sparrow/blob/ff4ff90bb2e403b2b41f01bb72672c74ef8cd52a/src/main/java/com/sparrowwallet/sparrow/transaction/HeadersController.java#L1180), but so are the cryptic responses from Core. If you can create a broadcasting error that Sparrow can handle with a better message, please open a new issue. 

> Okay, so you are basically suggesting that this issue should be closed then in favor of https://github.com/romanz/electrs/issues/397 ?

Yes, basically. I tried really hard to make this work in Sparrow, and it turned out to have more disadvantages than advantages for the reasons I described there.

Wrt to future solutions, I have a general view that we shouldn't add suboptimal solutions before they are really necessary. Rather, let's see how far we can get by making good engineering decisions with the current infrastructure. I'd like to see delayed (re)broadcasting support in Electrum servers, privately at first, and then publicly later. The resource requirements are not really that onerous in modern hardware terms, and can be capped. That would be my starting point.
