### ISSUE TITLE
Connecting to PayNym has incorrect fee rate

### ISSUE THREAD

**Issue by martinbarilik** [sparrowwallet/sparrow#1300]
I was just connecting to Sparrow PayNym and after confirming the transaction i was pretty surprised. Apart from announced 500 sats as connecting fee, transaction took 18000 sats for mining with fee rate 61 sats/vbyte which is whirpool premix fee rate atm. Currenct mempool fee is around 14 sats.

Is this expected behaviour ?

**Comment by craigraw** [comment]
What is your fee rate source set to?

You can preview a notification transaction and adjust the fee rate before sending. Sparrow uses the default fee rate for the configured fee rate source otherwise. Some fee rates sources (esp. Bitcoin Core) are less optimized than others to adjust quickly as the fee rate situation changes.

> Apart from announced 500 sats as connecting fee

This is not the fee - it's the minimum amount for the required output.

**Comment by martinbarilik** [comment]
Source is set to a local umbrel mempool. In this situation, there was no preview. I clicked connect and it created transaction behind the scene. Donating did show preview.

> This is not the fee - it's the minimum amount for the required output. 

But it is around that isn't it ?

**Comment by craigraw** [comment]
> Source is set to a local umbrel mempool (e.g. "Server" )

That means you are using Bitcoin Core, ultimately. See my previous response.

> In this situation, there was no preview. I clicked connect and it created transaction behind the scene.

I can't recreate this. Here is the dialog that is always shown:

<img width="472" alt="Screenshot 2024-03-07 at 09 12 54" src="https://github.com/sparrowwallet/sparrow/assets/862166/8246d1a6-914a-43cc-a203-7d57f31ca3d6">

> But it is around that isn't it ?

No, it depends on the fee rate.

**Comment by craigraw** [comment]
Up to you, but both mempool.space and oxt.me will react more quickly in a dynamic fee rate environment.

Closing this off.
