### ISSUE TITLE
"(?) Test Connection" has slow and misleading output when used with mempool.space fee rate source

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1307]
When using a Private Electrum server and setting the fee rate source to mempool.space I click the "(?) Test Connection" button. My internet connection doesn't actually have a route to mempool.space though. However, the output hangs on `Connecting to tcp://xxxxxxxxxx ...`. If I wait a few minutes, eventually that will go away and it will say `Connected to electrs .......` and the "Test Connection" button has a green check mark in it now.

There are a couple of problems:

1.  The initial hang on `Connecting to tcp://xxxxxxxxxx ...` is not right because it was actually not hanging on connecting to the electrum server, instead if was hanging on connecting to mempool.space. I'm mislead because I think there is a problem with my electrum server, but there really isn't. I don't expect this "(?) Test Connection" button to need to access mempool.space and I'm never told when it does get a good connection to mempool.space when my internet connection does actually have a route to mempool.space.
2. The fee rate source of mempool.space won't work since my internet connection doesn't have a route there, but it hasn't told me that that isn't available. I'm not sure if it has secretly fallen back to the "Server" option for the fee rate source or if it isn't going to have any fee rates available.

**Comment by craigraw** [comment]
> The initial hang on `Connecting to tcp://xxxxxxxxxx ...` is not right because it was actually not hanging on connecting to the electrum server, instead if was hanging on connecting to mempool.space.

So I understand correctly - you have configured mempool.space as a fee rates source, but you don't have a route to it?

The question is: What is better here - that Test Connection tests the connection using the same method as it would for normal connections, or that it skips certain parts of that method to be more "correct"? I believe the former is better, since it would be a poor user experience indeed if Test Connection worked, but the normal app connection did not.

Fwiw, I configured mempool.space to a non-routable IP on my machine and Test Connection worked fine, so your issue must be that packets are being dropped.

> The fee rate source of mempool.space won't work since my internet connection doesn't have a route there, but it hasn't told me that that isn't available. I'm not sure if it has secretly fallen back to the "Server" option for the fee rate source or if it isn't going to have any fee rates available.

Yes, Sparrow will fall back to the server's fee rate suggestions if mempool.space can't be reached, which always serve as a backup. This seems reasonable to me - suggesting that it is "secret" suggests there is something nefarious going on. What kind of behaviour were you expecting? The issue connecting to the fee rates source may be temporary, and is shown in the log file.

**Comment by AndySchroder** [comment]
You are right, I did not write that correctly. I had packets dropped and not the lack of a route. Sorry for not stating that correctly, I didn't realize it was that significant of a difference.

Maybe "secret" was not the best word to use, maybe "actually" would have been more appropriate.

Anyway, I think Sparrow wallet falling back the electrum server is the right thing to do. Maybe it is the right thing to do to test everything at once, I just think it needs to be more clear what the test is actually doing.


Here is what I would encourage:

1. Click "Test Connection"
2. Try to connect to the electrum server first, since that is what the output says right now. If there is a failure, indicate that. If there is a success, indicate that. Also, it makes sense to check for the electrum server before checking if fee rates are available from mempool.space because you can't fall back to anything on the electrum server whereas if mempool.space is not accessible and your electrum server is, then you can fall back to something.
3. If the fee rate source is set to mempool.space, say that it is next trying to connect to mempool.space. If mempool.space is available, show that as a success. If mempool.space is not available, indicate that it is not available and that the electrum server's fee rate is being used as a fall back. Also warn them that if they know that they won't ever have a connection to mempool.space, consider changing the fee rate source to "server" so that sparrow won't be delayed every time it tries to get fee rates from mempool.space and it can't.
4. When selecting fees when sending, say somewhere to let people know if the fee source is mempool.space or the electrum server. AND/OR, when mousing over the Connection toggle in the lower right, also say that mempool.space is used on a second line of the tooltop (if it is in use).

Possibly the flaw with my request here is that an electrum server can have a huge banner printed out, so maybe there needs to be a separate box for the electrum server test and the fee rate source test?

**Comment by craigraw** [comment]
I agree this could be improved, but it would be easy to overwhelm the user with different messages in Test Connection. I have some ideas - will update this once I have an approach I like.

**Comment by craigraw** [comment]
I've improved this in a805d9e0 so that Sparrow does not request fee rate estimates from the configured fee rate source (if it requires an external call) on the initial connection. This allows Sparrow to connect and start loading the wallets from the server immediately. The external call, if required, is performed asynchronously immediately afterwards. This means Test Connection is now just connecting to the configured server, and Sparrow additionally connects much quicker when the server is local.

**Comment by AndySchroder** [comment]
This is exactly what I want, but wondering for other people that are using the external sources if there should be some separate indicators saying if

- Fee rates source,
- Block explorer,
- Exchange rate source, and
- Software updates

are available? Maybe to the right of them you could have a little dot that is either red or green and then have a tooltip indicating the status of them? It seems as though you are automatically connecting to these sources in the background, so there is no reason to have a manual "Test Connection" button for each source. It does make sense to have a separate indicator for each source since they can all be different.

**Comment by craigraw** [comment]
That's just far too much for the average user IMO - and connectivity to these services is not a pain point I'm seeing either. Not overwhelming the user with information is important :)
