### ISSUE TITLE
Get Sparrow to forget a low fee transaction

### ISSUE THREAD

**Issue by gccollect** [sparrowwallet/sparrow#1338]
Is there a way to get Sparrow to forget a low fee transaction that is/will be dropped out of the mempool so that I can create a new transaction from that UTXO? Currently, Sparrow won't let me double spend that UTXO.

N.B. I am not looking to RBF. Just create a brand new transaction with that UTXO as input.

**Comment by ghscuuo** [comment]
I'm suffering the same thing.   Does this help?:
Test this in testnet.   In Sparrow 1.8.4, online, in your testnet wallet, Transactions tab, you should see your "Unconfirmed" transaction recent in your Date column.  Right-click that transaction, and you should get three options:
Increase Fee (RBF)
Cancel Transaction (RBF)
Increase Effective Fee (CPFP)
If desired, one or more of those options gives you the ability to change the output address(es).
There's no way to forget a broadcasted transaction.  While our low-fee transactions will eventually fall out of most default 300-MB mempools on mainnet, and perhaps most wallets that are attached to such default mempools, some huge mempools (like mempool.space) will keep spreading our transactions around like a bad smell.

Don't trust, verify all I said...

**Comment by craigraw** [comment]
Unfortunately not. Even if Sparrow could "forget" such a transaction, the Bitcoin network certainly won't be able to. So broadcasting any transaction that double spends any of the inputs (without RBF) will fail due to consensus rules. You will have to wait until the transaction is actually dropped out of the mempool (usually 2 weeks) or use RBF to replace it.
