### ISSUE TITLE
can't delete the first account

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1376]
We can have multiple accounts, but we can't delete the first account, even if it has no transactions. Other accounts can be deleted. I believe we should be able to delete all accounts.

Also, say your first account has a derivation path that you manually set of m/84'/0'/1/ (either because you typed that in or scanned a descriptor with that derivation path) and it has no transactions but you go to "Add Account" and then click discover and it finds an account with transactions in it with derivation path of m/84'/0'/0', we still can't delete the account with derivation path of m/84'/0'/1' because it was the first account created.

**Comment by craigraw** [comment]
Yes, this is due to the structure of the wallet database. It would be possible to write a lot of code to overcome this, but I think it's simpler to just require a new wallet to be created (which is simple enough).

In addition, allowing all accounts to be deleted suggests one can have a "wallet without a wallet" which creates a whole new set of issues.

Marking this as wontfix.
