### ISSUE TITLE
nuances with copy to clipboard

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1389]
A few things I've noticed about copy to the clipboard that could use cleaning up:

**Receive Tab**

1. Address Box: If you right click on the address, it has a little pop up that says "Copied!", but then it also shows the context menu underneath that that has "Copy" and "Select All". "Copy" is greyed out and "Select All" doesn't do anything.
2. Output Descriptor: Can't copy anything there.

**Addresses Tab**

1. Does it make sense to allow copy of the derivation path of each address when right clicking?

**Settings Tab**

1. Descriptor: If we right click, we can "Copy Value". That copies the abbreviated descriptor that doesn't have any formal meaning. Wondering if this option should be removed? I don't know why anyone should ever copy that over the real descriptor. I think having two options leads to confusion.
2. Descriptor: Wondering if it is useful to add the little copy icon like we have under the Receive Tab Address Box right side? I'm thinking it could go next to either the QR code icon or the "Show..." button.
3. xpub: Again, wondering if it is useful to add the little copy icon like we have under the Receive Tab Address Box right side?

**Comment by craigraw** [comment]
> Address Box: If you right click on the address, it has a little pop up that says "Copied!", but then it also shows the context menu underneath that that has "Copy" and "Select All". "Copy" is greyed out and "Select All" doesn't do anything.

Removed the context menu.

> Output Descriptor: Can't copy anything there.

Copy context item added.

> Does it make sense to allow copy of the derivation path of each address when right clicking?

I'm not sure, but it seems a bit unnecessary, so I'll leave it off for now.

> Descriptor: If we right click, we can "Copy Value". That copies the abbreviated descriptor that doesn't have any formal meaning. Wondering if this option should be removed? I don't know why anyone should ever copy that over the real descriptor. I think having two options leads to confusion.

The thinking here is to include both to differentiate them - otherwise it might be surprising if you were expecting to copy what you see, and you get something else. Here at least both options are added, so you can discover the difference.

> Descriptor: Wondering if it is useful to add the little copy icon like we have under the Receive Tab Address Box right side? I'm thinking it could go next to either the QR code icon or the "Show..." button.

I am always wary of adding more complexity, especially to an already complex screen. Also, see above - people might be confused to copy a full output descriptor when they are viewing the abbreviated one.

> xpub: Again, wondering if it is useful to add the little copy icon like we have under the Receive Tab Address Box right side? 

Same concern about complexity, but also it's going to difficult to do this (technically and visually) in a text area (as opposed to a textfield).

f1cddc28.
