### ISSUE TITLE
Unable to start mixing Postmix UTXOs

### ISSUE THREAD

**Issue by catman1111** [sparrowwallet/sparrow#1402]
Recently upgraded from 1.8.5 to 1.8.6 on Ubuntu 23.10 and when clicking 'Start Mixing' on Postmix UTXOs it says 'Starting Mixing...' for less than a second then returns back to the start mixing button and won't mix.

Removed the program and downgraded a couple of versions but having the same problem there as well.

Been using Sparrow along with the Coinjoin feature for over a month connected to and running a full node without any issues up until this point so not sure exactly what the problem might be.

Any help or insight is greatly appreciated.

![Example](https://github.com/sparrowwallet/sparrow/assets/168081442/4d985967-7ef8-4d2b-9ba3-351dfab4e792)

**Comment by uskrusader** [comment]
Did you catch the news yesterday?  Perhaps arrest of Samourai coinjoin coordinators has something to do with it?

**Comment by catman1111** [comment]
Ah just seen it, that could explain why, thanks.

**Comment by lasermind** [comment]
Nobody really knows how to go from here yet.

I also wonder why the new "decentralised Whirlpool coordinator" does not kick in. It was deployed on RoninDojos about three weeks ago. Maybe the new system simply does not work as intended, because it could not really be finished (or my understanding about it is wrong). Anyway, just guessing here.
