### ISSUE TITLE
[Feature Request] Reuse address detection

### ISSUE THREAD

**Issue by 4rkad** [sparrowwallet/sparrow#1423]
Sparrow might have an option to make a request beforehand to detect if the address you are sending to has been reused.

![image](https://github.com/sparrowwallet/sparrow/assets/55397917/4bc1cf40-761f-4ee7-90d9-5f5780c79ae0)

**Comment by craigraw** [comment]
There is unfortunately no way to do this generally (Bitcoin Core does not have an address index) and I'm not sure adding this wouldn't create more confusion that it's worth. After all, there is not much the sender can do if the receiver has chosen to use a static address - and as we can see from #1422, there is a real possibility of users thinking an address is not valid (instead of just reused).
