### ISSUE TITLE
Delayed start up at MacOS/M3

### ISSUE THREAD

**Issue by HenrikJannsen** [sparrowwallet/sparrow#1452]
On MacOS with Apple Silicon (I tested with a M3 chip) I get a 5 sec. delay at startup:
`2024-07-06 19:00:05,812 WARN [Thread-4] javafx [null:-1] Timeout while waiting for app reactivation`

Newer version of the javafxplugin have fixed the issue.
`https://mvnrepository.com/artifact/org.openjfx.javafxplugin/org.openjfx.javafxplugin.gradle.plugin/0.0.13`

**Comment by craigraw** [comment]
It appears this occurs on macOS 14 and is discussed in [JDK-8315657](https://bugs.openjdk.org/browse/JDK-8315657). The fix is upgrading to JavaFX 21.0.2 or later. It should be noted that doing so will prevent machines running macOS 10 from running Sparrow (old machines are unable to upgrade beyond Catalina).

I assume you are running from the command line. Does the issue occur when running the compiled v1.9.1 release?

**Comment by HenrikJannsen** [comment]
In Bisq we had the same issue and could get it fixed in a Java 17 setup. Updating the openjfx plugin was all what was needed. I am not that familiar with Sparrow code base to know if that works for you as well.

**Comment by craigraw** [comment]
This has been fixed by upgrading to JavaFX 22 in 49573d107578af4c4ff2004b75a82fb487316694.
