### ISSUE TITLE
Suggestion, winget support, windows arm64 support

### ISSUE THREAD

**Issue by jpph** [sparrowwallet/sparrow#1463]
Do you plan to add builds in winget for windows ?
also would be nice to have a aarch64 build for windows...
Regards

**Comment by craigraw** [comment]
> Do you plan to add builds in winget for windows ?

No plans to do so. Supporting package managers is generally labour intensive, although others are welcome to do so.

> also would be nice to have a aarch64 build for windows

This is simply too niche a combination to justify the additional work, even if JavaFX supported it - which it doesn't. Happy to revisit if this changes.

**Comment by jpph** [comment]
I have submitted package request to winget github help page. Lets see if someone pick it up. Thank you for your welcome!

**Comment by Dragon1573** [comment]
Seems assets in _GitHub Releases_ are compiled and built by _GitHub Workflows_. It would be nice to integrate [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser) to the build & release process.

Once a new version is released, a PR will automatically be submitted to `winget` source. Since this PR is created by the package publisher (or author), this can speed up testing process and easily be approved.

**Comment by craigraw** [comment]
Noted, but Github does not produce the final binary - currently, it still needs to be signed in a workflow outside of Github.

**Comment by jpph** [comment]
Thank you Dragon1573 for your help, "winget install sparrowwallet.sparrow" works very nicely!
