### ISSUE TITLE
Limit change addresses to 6 by default to maximize gap limit compatibility

### ISSUE THREAD

**Issue by benma** [sparrowwallet/sparrow#1478]
Hi

It seems the user can choose the change address from 20 available addresses. This leads to recovery issues on other wallets such as Electrum and BitBoxApp which use a default change scan gap limit of 6.

Please consider restricting to 6 so users are less likely to run into such scanning issues. As an alternative, you could show a clear warning about this problem when the user selects a change address after a gap of 6 unused ones.

**Comment by craigraw** [comment]
I see that Electrum is actually using a change gap limit of 10 as of 4.0.1, so I am not sure there is any agreement around the number 6.

I am personally in favour of making 20 the standard for both receiving and change - it makes for a simpler UI, since one setting can be used to control the configured gap limit for both chains. As useful as HD wallets are, gap limits are one of their issues, and ultimately user configuration of a higher gap limit will always be required in certain cases. Let's make that configuration as simple as possible.

**Comment by benma** [comment]
> I see that Electrum is actually using a change gap limit of 10 as of 4.0.1

This is unfortunate.

> I am personally in favour of making 20 the standard for both receiving and change - it makes for a simpler UI, since one setting can be used to control the configured gap limit for both chains. As useful as HD wallets are, gap limits are one of their issues, and ultimately user configuration of a higher gap limit will always be required in certain cases. Let's make that configuration as simple as possible.

On the other hand, higher default gap limits means slower account scanning times, which leads to worse UX, especially when there are many accounts and script types to scan for. Changing such configs should ideally be the exception, and done rarely. Compare it to scanning accounts, which happens on every use. The latter should be prioritized imho.

I don't see a good reason (except easier config) to have a change gap limit of 20. 6 seemed reasonable, do you now why Electrum bumped it?

**Comment by craigraw** [comment]
> On the other hand, higher default gap limits means slower account scanning times, which leads to worse UX, especially when there are many accounts and script types to scan for. 

I don't think loading times are appreciably different in Sparrow with batched JSON-RPC for the Electrum protocol, and Bitcoin Core uses a default `keypool` of 1000 for both receive and change chains, so there's no delay for that connection type either. Is the difference between 6 and 20 significant for the Bitbox app?

> I don't see a good reason (except easier config) to have a change gap limit of 20. 6 seemed reasonable, do you now why Electrum bumped it?

Looks [Lightning related](https://github.com/spesmilo/electrum/commit/cdecc4e3fa2119d052e047ddca98924f9fd606bf). 

From my pov, 6 seems a bit arbitrary - I was surprised to hear this number tbh. Another reason to use forward-looking unused change addresses is to construct multiple transactions that will only be broadcast in future.

**Comment by craigraw** [comment]
Given there is no general agreement on the number 6, and decreasing the default gap limit in a wallet would potentially cause loading issues, I'm closing this off. My recommendation would be to use a gap limit of 20, which probably the most widely accepted number for this parameter.

**Comment by SomberNight** [comment]
>> I don't see a good reason (except easier config) to have a change gap limit of 20. 6 seemed reasonable, do you now why Electrum bumped it?
>
> Looks [Lightning related](https://github.com/spesmilo/electrum/commit/cdecc4e3fa2119d052e047ddca98924f9fd606bf).

Yes, we bumped it when introducing Lightning as the wallet is now using them not just for change but also internally for e.g. LN commitment transactions. -- btw the original name from bip32 is external vs internal chain (not receive/change), it is just that usually the only "internal" use case is "change" :)

(If the channel counterparty force-closes, the to_remote output paying back to us needs an address to pay to. We are using change addresses for those, to ease recovery. However those pubkeys need to be chosen at channel-open time, for the lifetime of a channel, and we don't want to reuse them. And these addresses won't get used until that particular channel is closed. Hence the gap limit for change addresses limits how many channels the wallet can have open at any one time.)

**Comment by SomberNight** [comment]
> I am personally in favour of making 20 the standard for both receiving and change - it makes for a simpler UI, since one setting can be used to control the configured gap limit for both chains. As useful as HD wallets are, gap limits are one of their issues, and ultimately user configuration of a higher gap limit will always be required in certain cases. Let's make that configuration as simple as possible.

One counterpoint is that it is easier to come up with good usecases for having a large gap limit for receive addresses than for change addresses. E.g. a popular merchant might want a gap limit of 1000 for receive addresses, but would be fine with a gap limit of, say, 20 for change addresses. A non-trivial number of users do set very large gap limits because of those usecases, and many of these users use public servers.

>> On the other hand, higher default gap limits means slower account scanning times, which leads to worse UX, especially when there are many accounts and script types to scan for.
>
> I don't think loading times are appreciably different in Sparrow with batched JSON-RPC for the Electrum protocol, and Bitcoin Core uses a default keypool of 1000 for both receive and change chains, so there's no delay for that connection type either. Is the difference between 6 and 20 significant for the Bitbox app?

6 vs 20 vs 1000 might not matter for Bitcoin Core, or for Sparrow/Electrum when using a private electrum server.
But for public servers with a 1000+ users, even bumps from 6 to 10 to 20 might be noticeable for server load.

Subscribing to 1000+20 addresses, vs subscribing to 1000+1000 addresses, makes a lot of difference in public server load. And even to client "startup" times. So I think there is value in uncoupling the two gap limits.

I don't have a strong opinion re what magic number to use for gap limit for change addresses, anything in this range (<= ~20) seems reasonable. Having a default gap limit of 20/20 seems reasonable, but coupling the values I don't like.

**Comment by craigraw** [comment]
> I don't have a strong opinion re what magic number to use for gap limit for change addresses, anything in this range (<= ~20) seems reasonable. Having a default gap limit of 20/20 seems reasonable, but coupling the values I don't like.

Perhaps for the sake of general compatibility we could agree on a default 20/20 gap limit, and a decoupling of the two values? I'd be happy with that.
