### ISSUE TITLE
Lock information on Keystore Tab (Watch Only Wallet)

### ISSUE THREAD

**Issue by pvig0q1s** [sparrowwallet/sparrow#1484]
It is possible to edit information when Keystore is of type 'Watch Only Wallet'. 

Master fingerprint, Derivation, tpub / Vpub Fields are editable.

Like with other keystore types, the fields should be in locked state once the wallet is saved. Even though there is a fail-save (popup "Change Wallet Addresses?"), users should use the 'Replace' Button instead.

**Comment by craigraw** [comment]
> It is possible to edit information when Keystore is of type 'Watch Only Wallet'.

Yes. But the edited information is only used when the wallet is saved with the Apply button. If the user wants to go back to the original before saving, the Revert button is available.

> Like with other keystore types, the fields should be in locked state once the wallet is saved. Even though there is a fail-save (popup "Change Wallet Addresses?"), users should use the 'Replace' Button instead.

There is a significant difference here from the other keystore types - the fields for a watch only wallet are only editable by changing these fields. So requiring the user to use the Replace button not only seems less intuitive to me, but would require the user to start from scratch rather than just editing one of the existing fields.
