### ISSUE TITLE
[Feature]  In setting, button to set as default wallet for bitcoin protocol URI

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#150]
Everytime I install either a sparrow of electrum update the last install take over my browser default wallet.

Was only able to change this by editing the windows registry manually, big PITA.

The install process change this protocol association but sometime I just want to test a wallet without it taking over my default.

**Comment by craigraw** [comment]
Unfortunately this behaviour is controlled by the installer program, not Sparrow itself - therefore I cannot add a Sparrow setting to control this. The only way to do so would be to produce different installation binaries which did or did not include the registry changes. I don't think this is practical.

Running from source is probably the best solution to test the wallet without any registry changes, since the installer is not used.
