### ISSUE TITLE
Flickering and unable to connect

### ISSUE THREAD

**Issue by tansanDOTeth** [sparrowwallet/sparrow#1501]
This button always flickers and is unable to connect after leaving Sparrow on for a while in 1.9.1. I had to revert to 1.9.0, because the latest isn't reliable in terms of fetching latest data.

![CleanShot 2024-09-18 at 11 27 14@2x](https://github.com/user-attachments/assets/c604aa4f-d664-449e-a658-9101b4d643a6)

I'm using aarch64 on a mac M3

**Comment by craigraw** [comment]
There are no related changes between 1.9.1 and 1.9.0 ([see release notes](https://github.com/sparrowwallet/sparrow/releases/tag/1.9.1)) that affect loading a wallet, and no other reports of 1.9.1 being "unreliable" many months after the release. 

What is more likely is that your issue lies with the server you are connecting to. For example, most public servers impose resource limits and disconnect clients that exceed them. If you are loading any large wallets (wallets with many transactions) that may be the cause. It may also simply be the result of poor connectivity. The log file (Help menu) will indicate timeouts.

The best solution to this is to run your own Bitcoin Core node, and ideally your own Electrum server.

**Comment by tansanDOTeth** [comment]
> There are no related changes between 1.9.1 and 1.9.0 ([see release notes](https://github.com/sparrowwallet/sparrow/releases/tag/1.9.1)) that affect loading a wallet, and no other reports of 1.9.1 being "unreliable" many months after the release.
> 
> What is more likely is that your issue lies with the server you are connecting to. For example, most public servers impose resource limits and disconnect clients that exceed them. If you are loading any large wallets (wallets with many transactions) that may be the cause. It may also simply be the result of poor connectivity. The log file (Help menu) will indicate timeouts.
> 
> The best solution to this is to run your own Bitcoin Core node, and ideally your own Electrum server.

Oh my apologies if I offended you. I am not knowledgable on the changes. I am just reporting a bug that I found and my experience on 1.9.1. I don't know what the cause is, but I re-used the same servers in 1.9.1 as I did in 1.9.0. 1.9.0 is working as I would expect it to. However, I couldn't figure out what the issue was with 1.9.1 even after changing the server. 

Feel free to close this if you think it's a non-issue.

**Comment by tansanDOTeth** [comment]
> No offence taken. If you have relevant logs you can share, it might help.

Happy to provide it, but I'm not sure how to find those. Could you please share steps and I'll try to reproduce it?

**Comment by craigraw** [comment]
You can open the log file directly from the Help menu. Either copy and paste an excerpt here, or simply attach the whole file. No sensitive data is written to it.

**Comment by craigraw** [comment]
No response, closing.

**Comment by tansanDOTeth** [comment]
I haven't been able to reproduce this since I reported it, but if it happens again, then I'll know where to find the logs to update this thread.
