### ISSUE TITLE
Error saving wallet

### ISSUE THREAD

**Issue by swissdiver77** [sparrowwallet/sparrow#1514]
On Mac OS 15 i am trying to save a software BIP39 wallet to a different directory. 
I used the -d option on startup. The selected directory is something like /home/user/test
It was the same permissions as the default directory .sparrow. However when creating a 
new wallet I get the message: "Error saving wallet"

**Comment by Troy-ling** [comment]
@swissdiver77 
It sounds like you're running into a permissions issue even though the directories have the same permissions. Here are a few things you can try to resolve the "Error saving wallet" issue:
Check Directory Permissions: Make sure that the directory `/home/user/test` has the correct permissions for your user account. You can check this by running the command `ls -ld /home/user/test` in the terminal. The output should show that your user has write permissions.

**Comment by swissdiver77** [comment]
Thanks @Troy-ling : The permissions of said directory are indeed set to "drwxr-xr-x" and therefore do include write permissions for the current user. I wonder if I maybe need to create the directory called "wallets" or if sparrow will do that.

**Comment by Troy-ling** [comment]
@swissdiver77 Since the permissions look good, it's possible that Sparrow expects a specific directory structure. Creating a directory called "wallets" inside your specified directory (`/home/user/test/wallets`) might help. Sparrow should be able to save wallets in that folder. Try creating it manually and then restart Sparrow to see if it resolves the issue. If it still doesn't work, check if there's any documentation that specifies the required directory structure for saving wallets. Let me know how it goes!

**Comment by swissdiver77** [comment]
My bad. I mixed up MAC and Linux user path. I should have used /Users/user instead of /home/user. Sorry for the trouble & THANKS.
