### ISSUE TITLE
Sparrow hangs on QR keystore import

### ISSUE THREAD

**Issue by bc1easy** [sparrowwallet/sparrow#153]
When creating a new multisig wallet, Sparrow hangs on keystore import via QR code.

Hang occurs while webcam is active, until Sparrow is force-closed. Tested ~10 times with 2-of-3 and 1-of-2 multisig wallets, most frequently (but not exclusively) on import of final keystore. Possibly an M1 Mac hardware issue relating to the webcam / QR import functionality.

MacBookAir10,1 (arm64e)
macOS 11.4 (Build 20F71)
Sparrow 1.4.2
SeedSigner 0.4.1

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 2f15368.

The webcam library was performing unnecessary frequent (every 1 sec) rescans for connected webcams. If the rescan occurred at the same time as the camera close a deadlock occurred in the UI thread. These rescans are unnecessary since Sparrow just uses the default webcam anyway - in the unlikely event that the default webcam is changed I think it's reasonable for the user to be required to restart the app. A possible future feature may allow selection of the webcam, in which case a manual refresh of the connected webcams could be triggered.
