### ISSUE TITLE
Ability to choose webcam for Mac.

### ISSUE THREAD

**Issue by PrivacyHalt** [sparrowwallet/sparrow#154]
I have 2 other alternate USB webcams installed and when I don't have those attached. Sparrow doesn't default to the built-in mac camera.

**Comment by craigraw** [comment]
Thanks for the suggestion, implemented in ada45ee. The connected webcams will be shown in a dropdown at the bottom of the QR scanning dialog, from where the desired webcam can be chosen. This choice will be preserved across restarts of Sparrow (so long as the webcam is still connnected).

<img width="639" alt="Screenshot 2021-07-05 at 13 07 27" src="https://user-images.githubusercontent.com/862166/124462475-ff690080-dd91-11eb-83a8-7ec3d24d526b.png">

Note that due to issues in the webcam library, a restart of Sparrow will be required when a new webcam is connected.
