### ISSUE TITLE
Qualquer senha ?

### ISSUE THREAD

**Issue by Speranty** [sparrowwallet/sparrow#1540]
Gostaria de saber se houve alguma atualização na sparrow em relação a senha....antes qualquer senha você acessava a carteira, mas se digitasse errada aparecia outros endereços e se tivesse uma transação não aparecia.....agora qualquer senha entro na carteira e vejo minha transação.....agora to confuso.....ja perdi uns satochis por causa de senha errada.....houve alguma mudança?

**Comment by craigraw** [comment]
There has been no change regarding the passphrase - Sparrow still follows BIP39 in that regard, where any passphrase is valid and creates a separate wallet. Note the wallet password is different. Since the the 2.0 release however, Sparrow will warn if it detects that of the wallet history has changed:

<img width="472" alt="Screenshot 2024-07-17 at 12 19 34" src="https://github.com/user-attachments/assets/e7102d13-0518-4ba3-b390-43e004a450e7">
