### ISSUE TITLE
feature: use remainig amount for fees

### ISSUE THREAD

**Issue by NicolaLS** [sparrowwallet/sparrow#1552]
I created a transaction to two outputs and both required me to set an exact amount, I quickly calculated the amounts plus my anticipated fee before but of course the fee was a bit different so Sparrow created a dust output...

I know I could've set the fee manually, but I was in a rush. It would be nice to have a button that lets you just use the remaining amount as fee, in those situations I don't mind overpaying fees a bit instead of sitting on a dust output in my wallet now.

**Comment by ancoredev-sudo** [comment]
> I created a transaction to two outputs and both required me to set an exact amount, I quickly calculated the amounts plus my anticipated fee before but of course the fee was a bit different so Sparrow created a dust output...
> 
> I know I could've set the fee manually, but I was in a rush. It would be nice to have a button that lets you just use the remaining amount as fee, in those situations I don't mind overpaying fees a bit instead of sitting on a dust output in my wallet now.

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [LIVE SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by craigraw** [comment]
In general, the coin selection algorithm in Sparrow doesn't create dust outputs by design, and actually operates in the way you desire, increasing the fee unless a substantial (>100k sats) change output can be created. When this cannot be achieved (due to lack of available UTXOs) Sparrow does it's best to fulfil the desires of the user as reflected in the interface.

> It would be nice to have a button that lets you just use the remaining amount as fee

The cost of adding another button to an already complex screen is substantial, for what is in essence a niche use case. Sparrow tries to indicate the results of the the desired fee selection in the transaction diagram, and it's fairly simple to adjust the fee slider to achieve the result you wanted. I would argue this is a more elegant interface than another button (which in fairness, you may also have forgotten to use in your rush).
