### ISSUE TITLE
Support "Broadcast Raw Transaction" feature

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#16]
Sometimes, after signing a transaction, it doesn't get broadcasted and it holds on the final send screen with the progress bar going back and forth.

There's an option to download and save the signed transaction which allows the user to maybe broadcast it later but only from a different wallet.

Can we add a "Broadcast Raw Transaction" function on the Send Screen?

**Comment by craigraw** [comment]
You can save the the raw transaction either by cut and paste from the transaction hex display at the bottom, or clicking File > Save Transaction once the 'View Final Transaction' button has been clicked. This file can then be loaded later for broadcast.

Actually, the Broadcast does exactly what you describe - it simply calls the broadcast API on your Electrum server with the raw transaction. Sparrow then waits for the Electrum server to notify that there is a new transaction matching one of the addresses in the sending wallet, and retrieves the sent transaction from the mempool.

The question is why this is not working. I've noticed long delays sending when using Electrs, simply because that server gets quickly bogged down and I/O bound and the API calls described above take a long time to complete (or don't complete at all). I've filed an issue in the Electrs repo regarding this. If possible, try ElectrumX and see if it solves the issue (or have fewer wallets loaded in Sparrow, since every address subscribed to puts Electrs under additional pressure).

**Comment by craigraw** [comment]
After lots of further testing I think this is an Electrs issue. I have opened several issues on that project now - there are significant problems. I'll close this off now as I think the original feature request is already present as per the comment above.

**Comment by craigraw** [comment]
Sparrow now schedules an explicit check of the relevant script hashes after a broadcast to ensure that the broadcasted transaction is picked up.
