### ISSUE TITLE
autocomplete of bip39 words false positive

### ISSUE THREAD

**Issue by djpnewton** [sparrowwallet/sparrow#20]
If you are typing in a bip39 word that has another valid bip39 word that is a prefix (eg 'youth' and 'you') the software will say there are no other possible words when you type in the shorter word

**Comment by craigraw** [comment]
This was intentional to allow the user to tab on to the next word. I felt the UX when keeping the word suggestion list open was poorer. It might be possible to intercept the Tab key and close the suggestion list to move to the next textfield, but I'm not sure it's better than the current approach which has the advantage of feeling a little 'cleaner' as you type and tab.

Open to thoughts though.

**Comment by 6102bitcoin** [comment]
My thoughts: It would be useful to continue to show the available words in-case notes are damaged and the remaining characters are unclear. At any time the user can press enter to select the shortest word from the list (`you` in this case). Use of color (blue/red border) makes it obvious to a user when the word they have currently entered is valid.

Outstanding Action: Show all applicable words given input provided (don't stop when a valid input is reached)
Proposed Priority: Low

**Comment by craigraw** [comment]
This is a minor issue I think, and my comment above stands - in practice it doesn't feel "completed" when a the suggested word list is still open, which introduces doubt into the process. Hard to describe, but I'm not keen to implement this for the rare case of a damaged seed list. Closing this off.

**Comment by craigraw** [comment]
Yes - turns out I was wrong, and @haakonn's improvement sorts this out nicely.
