### ISSUE TITLE
Whirlpool - Premix UTXO - input rejected

### ISSUE THREAD

**Issue by rjbiii** [sparrowwallet/sparrow#207]
I have two UTXO's in whirlpool at the moment - one is mixing successfully (it's in the post mix tab with a count of 4) but the other is stuck in the premix tab with an error saying "input rejected". I checked the documentation and there doesn't seem to be any guidance about what to do in this situation. Can this be added to the documentation?

If I go to the premix tab and select the UTXO that says input rejected, and then click stop mixing, will Sparrow stop mixing just this UTXO, or does the stop mixing button stop all mixing?

Some information that may be relevant - I'm using my umbrel as my electrum server, so everything is over tor. I'm using sparrow on Pop OS, and used the debian installer.

Edit: I just found that I can right click -> start mixing on that UTXO. Trying that now, hopefully this one works.

**Comment by craigraw** [comment]
> Trying that now, hopefully this one works.

Hope that works.

Generally "input rejected" is due to too many failures, in example when client get disconnected multiple times during a mix, causing too many mix failures in a short period of time.

There is an automatic temporarily ban protection to protect coordinator against attacks or unstable clients. Such ban automatically expires after some time (about 12h).

You can email support@samourai.io with the details of your UTXO if you want to get unbanned quicker. I'll take a look at improving the documentation on this aspect.

**Comment by craigraw** [comment]
New section added to the mixing doc: https://sparrowwallet.com/docs/mixing-whirlpool.html#understanding-mixes

I'm going to close this off, but add another comment if there is still an issue here.
