### ISSUE TITLE
Using Sparrow for first time, creating new wallet has convoluted non-linear flow

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#211]
![image](https://user-images.githubusercontent.com/388716/134753758-83d767e5-19ce-4135-bbcc-7e0c2fb96871.png)

I suggest NEW to a more prominent option, Like being first of these 4 options, few people have a hardware wallet.

![image](https://user-images.githubusercontent.com/388716/134753828-91a62246-d198-4ad3-872f-ccd4c2faeb34.png)

Being switched to a page that doesn't have any visible NEW / Generate option.

![image](https://user-images.githubusercontent.com/388716/134753895-77a6c451-2366-424e-86c0-a172bb316c3d.png)

Only at this point do we see "Generate New"

![image](https://user-images.githubusercontent.com/388716/134754066-4e1c3692-68be-4b9a-a1a2-e4dbe42fce55.png)

No idea what that step is about, "Create Keystore" Seems like a step only to teach the word "Keystore", still no idea what that's about.  How about "Generate Wallet"?

Although the suggested next button is highlighted in blue, it's very overwhelming to still have all other options and buttons visible.

![image](https://user-images.githubusercontent.com/388716/134754328-754e3c55-b348-440e-bd32-74a05ae34eeb.png)

One more step, What if the text field would be grayed out and clicking "Custom derivation" would make it editable with the option of one of 9 sub-accounts as a dropdown.

![image](https://user-images.githubusercontent.com/388716/134754562-c39abf2f-2305-4cad-9ad5-2b4fd00b01a0.png)

![image](https://user-images.githubusercontent.com/388716/134754627-32ba04db-ba5d-4807-a5f6-c581ee3a8372.png)

One more step, Now sure what the "Revert" button would do, Edit last step? Well, no It just deleted everything and bring us back at step one. Should be named "Clear", "Revert" sounds like Undo (last step) to me.

![image](https://user-images.githubusercontent.com/388716/134754771-8b7e078a-9e63-4d41-b030-f8913c83ccf7.png)

Nothing seems to happen after clicking "Apply" and not clear next that someone has to manually toggle that tiny gray button at the bottom.

Also seems like the first time I toggle connect it never end up connecting.
![image](https://user-images.githubusercontent.com/388716/134754890-4b7fab84-4264-4cfd-a939-9578e6a91073.png) Stuck on showing this, shouldn't the attempt eventually time-out, retry or something?

Might want to jump the user to Transaction, Receive, or Addresses panel to they can see something has happened and made available.

**Comment by craigraw** [comment]
I understand where you're coming from - a UI can't please everyone, I've found. But these are my rationales:

> few people have a hardware wallet

Actually, I believe Sparrow is usually used with a hardware wallet.

> Being switched to a page that doesn't have any visible NEW / Generate option.

Adding this would direct people down a single route. Often for example, you want to restore a seed not create new one. BIP39 seed? Electrum seed? Xprv? Lots of choices.

> How about "Generate Wallet"?

There is a problem in the Bitcoin wallet space that everything is called a wallet. What happens when you use multisig - do you call that a "wallet of wallets"? It gets very confusing. Sparrow (and Electrum) use the word "keystore" to help identify sources of keys.

> it's very overwhelming to still have all other options and buttons visible.

It might be an idea to remove the other options at this point. But it could also be disturbing to have UI items vanish in unpredictable ways.

> Also seems like the first time I toggle connect it never end up connecting.

Blockstream's server is often very slow. You can configure another.

> One more step, What if the text field would be grayed out and clicking "Custom derivation" would make it editable with the option of one of 9 sub-accounts as a dropdown.

That disables the textfield at the expense of enabling the Custom Derivation button. I don't think it's an improvement.

> "Revert" sounds like Undo (last step) to me.

That's exactly what it is. In this case, revert to the original state when you first created the wallet. Once the wallet has been saved, any changes you make to the Settings can be undone with the Revert button.

> Nothing seems to happen after clicking "Apply" and not clear next that someone has to manually toggle that tiny gray button at the bottom.

Creating a wallet and connecting to a server are independent - there are good reasons to create a wallet and stay offline. The introduction wizard takes some time to explain connecting to a server.

> Might want to jump the user to Transaction, Receive, or Addresses panel to they can see something has happened and made available.

The status bar does suggest this once connected, but I don't believe in changing the UI without the user requesting it.

**Comment by 6102bitcoin** [comment]
AFAICT these suggestions (although well intentioned) are a personal preference which conflicts with the design and intention of Sparrow

**Comment by Transisto** [comment]
Re, I'm creating a wallet to reproduce a bug, 

I've been using sparrow for a little while and I got completely lost trying to create a wallet again.

I don't think it's normal to click **Enter** to find **Generate**

![image](https://user-images.githubusercontent.com/388716/156208179-67550fa7-ebcf-4544-af05-115de2404b25.png)


![image](https://user-images.githubusercontent.com/388716/156208326-55512486-3ed5-4914-abd5-317dc7f8262d.png)

**Comment by craigraw** [comment]
Improved in 1a9c6f8 and followups:
<img width="762" alt="Screenshot 2022-03-02 at 17 14 39" src="https://user-images.githubusercontent.com/862166/156390271-8205e10b-9836-4adb-b358-f35d2c7a4361.png">
