### ISSUE TITLE
Unable to connect Sparrow to Bitcoin core on same machine

### ISSUE THREAD

**Issue by btcschellingpt** [sparrowwallet/sparrow#216]
The RPC connection to Bitcoin Core appears to fail from Sparrow with default configuration for both products and both running on the same machine.

Bitcoin Core v0.22 out-of-the-box, running on Ubuntu 20.04 - current patch level.
Sparrow v1.5

bitcoind started as a daemon, no other parms

Attachments:
- sparrow.log and bitcoin.conf (.zip archive)
- bitcoin's debug.log

[2021-09-26 bitcoin core connection issue - btcschellingpt.zip](https://github.com/sparrowwallet/sparrow/files/7230993/2021-09-26.bitcoin.core.connection.issue.-.btcschellingpt.zip)
.
[debug.log](https://github.com/sparrowwallet/sparrow/files/7230996/debug.log)

**Comment by craigraw** [comment]
This bug was introduced for v1.5.0 due to #181 - in an attempt to avoid creating empty wallets in Bitcoin Core, whenever no wallets are loaded in Sparrow, or the Test Connection functionality is used, Bitcoin Core throws an error if the Core wallet has not already been created.

The workaround is to create a wallet in an offline state and ignore the 'Test Connection' functionality for now. Once the wallet has been created, use the server toggle in the lower right to enable the connection. The wallet will then be created in Bitcoin Core. Once it has been created for the first time, all functionality should work as it did pre v1.5.0.

**Comment by craigraw** [comment]
You can also simply create the Bitcoin Core wallet with
```
bitcoin-cli createwallet "sparrow"
```

**Comment by 6102bitcoin** [comment]
Long term is the intenion to guide the user through this / automate it as was done previously (re-introducing the blank wallet 'bug')?

**Comment by craigraw** [comment]
> automate it as was done previously

Yes - this has been fixed. Closing.
