### ISSUE TITLE
Postmix can get received further than the default gap limit

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#226]
It left 30 empty spots, was able to see them by increasing the gap limit.

It could be caused by the bug that banned most UTXO form the coordinator.

Whirlpool allow to mix up to 70 UTXO at once, if the mix isn't done sequentially maybe that can leave a big gap in the address space.

**Comment by Transisto** [comment]
Also noticed that there isn't two address used in a row, 

Best case scenario it's skipping one.
![image](https://user-images.githubusercontent.com/388716/135110727-a6cf9ee3-1f1e-4320-9195-4893203e0cee.png)

**Comment by craigraw** [comment]
> It could be caused by the bug that banned most UTXO form the coordinator.

This is correct - although it isn't really a bug, but more a consequence of the way the coordinator works. The ZeroLink protocol requires coordinator to reject any "known" postmix address to preserve clients privacy. So, when the connection to the coordinator is lost because of an unstable network, the client must choose the next postmix address. This can cause some unused addresses - in this case a block that is larger than the gap limit.

> Also noticed that there isn't two address used in a row,

This is to avoid conflict with the Samourai Android client. The Android client uses odd indexes, and all desktop Whirlpool clients (CLI and Sparrow) use even indexes. 

Given the above, I think it makes sense to double the default postmix gap limit to 40. Implemented in https://github.com/sparrowwallet/drongo/commit/9a9a1b925461ee2a8ae7f6885309b0babd4b6767.
