### ISSUE TITLE
Loading transaction much slower than electrum

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#28]
On electrum I see it syncing in blocks of about 120 addresses at a time.
about 2 blocks per second.

On sparrow it loads it 1 by one at about 8 per seconds.

It does 100 then it load blocks then it load transaction [hex]

then it does another 100 ...

Should take about an hour at this rate... 

Got stuck on this:
![image](https://user-images.githubusercontent.com/388716/96770012-f411a880-13ad-11eb-9677-71a073a1c194.png)

After disconnecting and reconnecting it seems to not do it it bocks of 100 anymore, It stopped at about 600 then started again from 0

**Comment by craigraw** [comment]
This is a large wallet!

Unfortunately with large wallets, the server software matters. In particular, Electrs has significant unresolved issues (see the Issues on that project) which cause it to respond increasingly poorly as as the number of used (subscribed) addresses increases. Electrum works better (I think because it downloads and stores all the block headers in advance) but I am hoping that Electrs can resolve its issues before putting significantly more work into this area. With a wallet of this size, at this stage I would recommend using ElectrumX which is uses batched calls and is significantly faster.

**Comment by 6102bitcoin** [comment]
Outstanding Action: Monitor Electrs progress on this issue (multiple issues, [example](https://github.com/romanz/electrs/issues/146)
Priority: Low

**Comment by craigraw** [comment]
Sparrow's performance should now be similar to Electrum's - specific changes regarding calculation and caching of script hash statuses are present as of v1.4.1. The only difference I'm still aware of is that Electrum downloads and stores all block headers ahead of time, but this should not cause a significant difference in wallet loading time.

Note that for proper testing on Electrs, it should be restarted before testing each client independently as it bogs down with the number of script hashes subscribed to. Multiple wallet loads should also be performed on each client, as initial loading and subsequent loads have different data needs.

It would be good to repeat these tests on the large wallet above using the current release to verify if things have improved.

**Comment by 6102bitcoin** [comment]
Recent update (v0.9.0) to Electrs should have made an improvement here. If you are building from source please can you report back whether this has helped @Transisto. Alternatley, if you are using prebuilt binaries look out for the next release which looks like it will be using v0.9.0

**Comment by 6102bitcoin** [comment]
From my experience it is significantly faster. Are you sure you are using the latest Electrs?

**Comment by craigraw** [comment]
This is now an old issue, but I wanted to test the hypothesis against the current HEAD (latest code) of both Sparrow and Electrum. I used a large wallet (6k+ used addresses) and connected both to an instance of Fulcrum 1.6.0 running on the local network. I then created the wallet on both platforms (consecutively, not simultaneously) to see how long it would take to display the latest transactions. I did not change the gap limit from the default 20, although I suspect this would have improved performance substantially on Sparrow.

Sparrow took 46s.
Electrum too 3m51s.

This makes sense, since Electrum is not using batched queries, resulting in far more communication and other overhead.

Given the above I am closing this issue off. Sparrow is simply much faster than Electrum.
