### ISSUE TITLE
mDNS name resolution

### ISSUE THREAD

**Issue by jblachly** [sparrowwallet/sparrow#286]
The resolver used in Sparrow wallet does not recognize multicast DNS (mDNS; names ending in `.local` emitted automatically either by Bonjour on OS X or by `avahi-daemon` on linux/freebsd and ending). This makes it difficult to use Sparrow in an environment where I have virtual machines or containers running components of my software stack in isolated instances but with unique (and potentially changing, although the DHCP server does a good job in general not doing this) virtual environments.

With latest Sparrow release on Mac OS I can confirm that I can connect to a bitcoin full node running on LAN (192.168.1.0/24) by IP, but not by mDNS name (`bitcoin.local` or whatever) -- whereas other software on this machine is able to resolve the .local domain correctly via mDNS.

Thank you for considering; I recognize this may be a problem inherited from a library dependency or even something in the Java stdlib.

**Comment by craigraw** [comment]
Fixed in 487be2e. It turns out this was only affecting Bitcoin Core connections using the Rust BWT library. When connecting to Private Electrum servers, Java resolves the mDNS hostnames without any trouble. This has been fixed by resolving the hostname to an IP in Java before passing it off to BWT.

@shesek something to look at in future perhaps.
