### ISSUE TITLE
Feature request: "Show QR" button after signing loaded transaction

### ISSUE THREAD

**Issue by raymondclowe** [sparrowwallet/sparrow#295]
Please consider adding another Show QR code button after signing of a loaded transaaction to facilitate the workflow explained below.

![image](https://user-images.githubusercontent.com/68897994/139532645-e23a935b-a6c4-46e4-84ba-55254cf7827f.png)

This is useful when doing an offline transaction signing where both the online and offline device are Sparrow.

At the moment I can :

* Online machine:
    * Use an online Sparrow to create the unsigned transaction.  
    * Display it as a QR code
* Offline machine
    * Use File / Open transaction / From QR
    * Sign the transaction
    * Show as QR code **<-- this is the missing step**
* Online machine
    * Use File / Open transaction / From QR
    * Broadcast

This allows using two PCs to quickly and conveniently do offline signing without using cards or removable media.  

In my case the offline machine is a airgapped laptop booted with TAILS linux USB while the online is a Windows machine connected.  It is also possible to do with one machine, using a phone to take pictures of the QR codes (or video if they are animated) and hence move the data from one step to the next.

Thanks.

**Comment by craigraw** [comment]
Added in 25dd044, thanks for the suggestion. It's added as a menu item in the File menu rather than a button to keep the UI cleaner. That makes it available for all transactions and PSBTs as well.

<img width="284" alt="Screenshot 2021-11-03 at 14 10 30" src="https://user-images.githubusercontent.com/862166/140057745-1bfe0e6b-3b1c-43b7-a5df-b3cc1d337fbd.png">

**Comment by igonro** [comment]
Hi @craigraw 

Is this working properly? I've tried scanning the QR code with Blue Wallet broadcast tool, but it doesn't work.
When saving the TX in a file, it works.

I've scanned the QR, and it looks like the result is UR:BYTES followed by some uppercase characters. Should not the result be in hex format?

P.S.: I'm new to all of these things, so I'm not sure what's the standard when sharing QRs, nor whether the error is on Blue Wallet or Sparrow (or maybe they're both right but using different implementations).

Thanks!

**Comment by craigraw** [comment]
@igonro Sparrow uses the Blockchain Commons UR2.0 specification for displaying QR codes, especially when the data is of variable length and may not fit into one QR code. Simply encoding hex characters means large transactions cannot be exported. Ideally other wallets would detect and understand the UR2.0 format for this use case, as it is already broadly used for the transmission of PSBTs.

**Comment by AndySchroder** [comment]
This is a super useful feature, but I think the original suggestion of @raymondclowe where there is a button to the left of the "save final transaction" button should exist that says "Show Final Signed Transaction QR" in addition to the File menu item. You might also want to change the File menu item to use that same label to be more clear that you are showing a QR of the Final Signed Transaction. It took me a long time to figure out where that menu item was on my first try. Having the button to the left of the "save final transaction" button would seem to me like a more consistent UI with Online machine because you have a "Show QR" and "Scan QR" button there. Also, on the online machine, the workflow would be a bit clearer to me if the "Show QR" were changed to say "Show PSBT QR" and the "Scan QR" were changed to say "Scan Final Signed Transaction QR".

**Comment by craigraw** [comment]
With all UI suggestions, I must consider the needs of the few who might find additional buttons convenient with the needs of the many who might find additional buttons confusing. I've tried hard to keep the two button format for post signing - extracting, broadcasting and saving the final transaction depending on online status to keep the UI from changing too much. 

The text "Show Final Signed Transaction QR" is probably too long as well. In all cases, Sparrow tries to reflect in menu commands what in displayed onscreen, and this is true for the transaction state as well, so once the transaction has been finalized, this is what will be exported.
