### ISSUE TITLE
Transactions fail to load in Postmix wallet

### ISSUE THREAD

**Issue by chrisacannon** [sparrowwallet/sparrow#305]
The Postmix section in one of my wallets will not load, showing message, "Error loading transactions: Failed to subscribe to path: m/0/...".

The Deposit, Premix, and Badbank sections of the same wallet load their respective balances/histories successfully.
![SparrowTransactionLoadingError](https://user-images.githubusercontent.com/74935375/141170088-9ff2e959-6b0c-4e31-9309-e2fcd044f444.PNG)

**Comment by craigraw** [comment]
This error occurs because the Postmix wallet is larger (more used addresses) than the other wallets. As such, it's not a Sparrow issue, but a server issue. The server is having trouble dealing with the size of this wallet.

Are you are using Electrs pre v0.9.0? If so, upgrading to the latest release will probably solve this.
