### ISSUE TITLE
Wrong labels when tx to multiple recipients

### ISSUE THREAD

**Issue by urza** [sparrowwallet/sparrow#359]
Create new transaction to multiple recipients (addresses), add label to each recipient.

At confirmation screen (signing transaction) only the label for first recipient is shown incorrectly for all outputs.

**Comment by urza** [comment]
Also, when the transaction is broadcasted, in wallet transactions tab, it only shows the first recipient label, the other labels are lost.

**Comment by craigraw** [comment]
> At confirmation screen (signing transaction) only the label for first recipient is shown incorrectly for all outputs.

Technically, this is because Sparrow is loading the PSBT it has generated, and the PSBT format does not contain labels. However, there is now a workaround in cd91aff to display the correct labels when multiple recipients are sent to.

> Also, when the transaction is broadcasted, in wallet transactions tab, it only shows the first recipient label, the other labels are lost.

The transaction itself can only have one label, so the label of the first recipient is chosen. This matches the name in the transaction tab. The outputs of the transaction now get labelled with the correct payment label should one be applicable. 3776fba
