### ISSUE TITLE
[UX] Nothing comes after collab. tx broadcast

### ISSUE THREAD

**Issue by elkimek** [sparrowwallet/sparrow#371]
When doing a collab. tx, nothing appears after the broadcast step. Right now when user clicks on the broadcast the window just disappears which is a bit confusing. It would be helpful to add one more notification step "Cahoots Success" or something like that and refresh the wallet automatically as that doesn't happen neither and it's not clear if the transaction was sent or not.

Thanks :)

**Comment by craigraw** [comment]
Once the Broadcast button is clicked, the server should almost immediately notify Sparrow of the new transaction in the wallet as it enters the local mempool. This should create the normal "new transaction" popup notification in the top right. Do you feel this is insufficient? Or is it simply not happening?

If this is not happening, it's a server issue (any errors doing the actual broadcast will be reported in Sparrow).

**Comment by elkimek** [comment]
Likely server issue then. It didn't happen at all last few times and I had to trigger the refresh manually to see the outgoing tx. Anyway I feel there should be one last step during the collab process as described.

**Comment by craigraw** [comment]
I'd like to try get the original problem fixed before adding additional UI - in any case, Sparrow can't show "Cahoots Success" if it does not receive confirmation that the transaction has been successfully received in the mempool.

**Comment by craigraw** [comment]
Ok, in 8fb7f54 I've added a broadcasting step the collaboration initiator dialog. Sparrow will now actively poll the server a number of times after broadcasting so that it does not rely on the server notification (it does this for normal transaction broadcasting too). Once the transaction has been received, the initiator dialog will indicate success.

<img width="842" alt="Screenshot 2022-01-07 at 09 18 35" src="https://user-images.githubusercontent.com/862166/148510143-06b0ada7-0af8-45d3-a716-d3ce31e3f12c.png">

<img width="842" alt="Screenshot 2022-01-07 at 09 16 52" src="https://user-images.githubusercontent.com/862166/148510170-3917f170-fbd3-4fe8-9bae-5e46efe9126e.png">

**Comment by elkimek** [comment]
Nice, thanks!
