### ISSUE TITLE
[Feature] Two party spend Stonewall2x

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#406]
Right now if you are a collaborator in a Stonewall2x (i.e. the one helping a Paynym to send a transaction) the benefit for the collaborator is an increased anonymity set of the participating utxo(s). 

An enhanced Stonewall2x could be a transaction where the collaborator utxo not just participates but is actually used for a spend (like a two party collaborative batch spend).

For Example:

- Paynym who initiates enhanced Stonewall2x needs to spend 0.6 BTC
- Collaborator who wants to help has also to spend or maybe wants to send bitcoin to another address he owns, say 0.2 BTC 

| Inputs  |   |  Outputs |
|---|---|---|
|   |  |  ------------  0.1 BTC Collaborator - Change |
| 0.9 BTC Collaborator ------------   |    |  ------------ 0.2 BTC  Collaborator - Spend |
|  |    |  ------------  0.6 BTC Collaborator - Decoy Paynym Spend  |
|   |  Transaction   |
|   |    | -----------   0.3 BTC Paynym - Change |
| 1.2 BTC Paynym -----------------   |    |  ----------- 0.6 BTC Paynym - Spend |
|   |    |  ----------- 0.3 BTC Paynym - Decoy Collaborator Spend  |

Benefit as far as I can see: From the outside it isn't clear who spends which amount and - if the spend amounts aren't "round" numbers - it isn't clear which of the outputs are change and spend (i.e. the benefits from Stonewall & Stonewall2x transactions).

The problem is that 6 outputs make it distinguishable from a Stonewall or Stonewall2x which is quite a negative. A further question is how the total amount each participant has to provide is communicated.

Are there any privacy or logical misses from my side in such an approach? Is this technically possible to implement via Soroban?

**Comment by craigraw** [comment]
Thanks for the suggestion. I don't think there is anything logically wrong with it - effectively we are just splitting up the collaborator's change so that some of it becomes a payment. I'm not too keen on reducing the anonset of normal Stonewall transactions though - perhaps in future when that anonset is big enough, it may make more sense. It also introduces additional UX complexity which is a consideration. 

On balance I'm going to shelve this, but it could be reopened later.
