### ISSUE TITLE
[Feature] AOPP Relay 

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#411]
The Address Ownership Proof Protocol (AOPP) aims to "for providing proof of ownership of an external wallet's address".

AOPP is typically used by exchanges to "prove the withdrawal is going to the intended recipient". 

Unfortunately for those exchanges, a user requesting a withdrawal with a 2 way comunications channel with the true recpient can dupe AOPP trivially. Exchanges can't verify that the user has no such channel, therefore AOPP fails to achieve it's implied goal.

AOPP used in this way by exchanges is an imposition on the user who is forced to use a wallet which supports the protocol.

It sets a bad precident - more information than is strictly required to receive bitcoin (just a valid bitcoin address) is demanded by the exchange. 

# AOPP Relay 

Adding an AOPP Relay feature which automates the below procedure would demonstrate the error made by exchanges using AOPP.

Bob requests a connection to Alice 
Alice confirms connection and sends Bob an address
Bob requests a withdrawal from his exchange to the address
The exchange challenges Bob to sign
Bob forwards the request to Alice
Alice signs and sends the signed response to Bob
Bob passes the signed response to the challenger 

## Potential for additional relays:

Unbeknownst to Bob, Alice could actually be forwarding to Charlie

**Comment by lclc** [comment]
Providing an ownership proof is not something exchanges want to do, but, in Switzerland, have to do.

From the FINMA Guidance 02/2019, Payments on the blockchain:
"A transfer from or to an external wallet belonging to a third party is only possible if, as for a client relationship, the supervised institution has first verified the identity of the third party, established the identity of the beneficial owner and **proven the third party's ownership of the external wallet using suitable technical means.**"

For FINMA, suitable technical means either:
1) Asking the user to take a screenshot of his wallet
2) Asking the user to send small amounts to prove ownership
3) or, asking him to sign something with the private key of that address (manually or with AOPP).


If this regulation makes sense or not is another topic (and most, if not all, Bitcoiner would probably say No), but it’s been in place since 2019, making withdrawing Bitcoins from Swiss exchange/broker/bank challenging. That’s why we came up with AOPP (2 years later) - to make withdrawing from a Swiss exchange/broker/bank (such as Pocket Bitcoin, Bittr, or Relai) as easy and seamless as before this regulation.


What you describe is certainly possible, and has been pointed out to the regulator, but it won't change their mind (otherwise, Screenshotting a wallet wouldn't be OK).

**Comment by craigraw** [comment]
AOPP has been removed completely from Sparrow in c81f3d9.

@lclc I appreciate your situation, but I think the argument of a slippery slope to creeping KYC is compelling. Standard Bitcoin message signing remains present in Sparrow, even if AOPP does not. 

Please could you remove any reference to Sparrow on aopp.group. Thank you.

**Comment by kn0wmad** [comment]
Thanks for squashing that bug @craigraw - it seems to have crept into several wallets.
