### ISSUE TITLE
How to calculate Output Descriptor checksum

### ISSUE THREAD

**Issue by Francisco-DAnconia** [sparrowwallet/sparrow#431]
Was pleasantly surprised to see a full Output Descriptor. Thanks!

However, I can't figure out how to calculate the checksum so that it corresponds with the reported value. 

bitcoin-cli getdescriptorinfo returns an error code: -5  When passing in the range descriptors at the end "<0,1>/*" 

Picking 0/* or 1/* result in different checksums than Sparrows

Is there cononical syntax for using getdescriptorinfo to match Sparrow's checksum? Or is there another preferred method?

**Comment by craigraw** [comment]
Sparrow uses the canonical method of representing a PR (one descriptor instead of two) as described in https://github.com/bitcoin/bitcoin/pull/22838. Unfortunately, that PR has not been merged yet. 

So, the way to create the two individual descriptors is to do so manually and computing the checksum for each with `bitcoin-cli getdescriptorinfo`.
