### ISSUE TITLE
Small RawTransaction UI quibble.

### ISSUE THREAD

**Issue by Francisco-DAnconia** [sparrowwallet/sparrow#443]
The color coded output for getrawtransaction is awesome. I learned so much,  I hesitate to mention this - but your attention to detail and UI design is so refreshing - perhaps this minor item will be of interest to you.

It would be really nice to update the color coding of the hex output depending on the current selection. 

For example, selecting "Input #0" shows the outpoint in blue which matches the hex. However, {signature} is green, yet the signature text retains its magenta color from the selection of the overall transaction [1bdd03]. It would be cool, to show the signature hex in green to match the color displayed in the "Witness" field.

Likewise, Selection "Output #0" It would be nice if the {wpkh}'s brown color was also reflected in the hex output.

Also, when I copied the hex text on macOS (only place I tried) I did not get the colored version, but just uncolored text on the clipboard.

![Signature](https://user-images.githubusercontent.com/33098368/155860605-7b7b00fe-15ab-4dd4-b0da-015b0372a481.png)
![WPKH](https://user-images.githubusercontent.com/33098368/155860609-449e3092-d459-4379-ac49-c8fdaa124c8f.png)

**Comment by craigraw** [comment]
Thanks for the suggestion. I've implemented the green witness signature color coding in 281fad5.

Wrt to the ScriptPubKey, it may actually be more confusing to make it brown - since the ScriptPubKey includes the `OP_0` opcode, and the `<wpkh>` does not. So is it blue or brown? On balance I think better to leave as is.

Wrt to copying the hex, I would prefer not to make this a rich text copy, since copying and pasting the transaction hex from Sparrow is a key area of "WYSIWYG" transparency that rich text encoding would reduce.
