### ISSUE TITLE
Funds sent to Sparrow generated address confirmed, funds never arrives

### ISSUE THREAD

**Issue by patrxck1** [sparrowwallet/sparrow#459]
I was sending funds to my sparrow wallet and when I copied the address it pasted "38pBm8pU2KkkBeCczLhTwXRCXD3W91Jha4". Anytime I generate a new address this one copies as well. I made this wallet as a legacy wallet accidentally but I don't think it would affect me receiving btc.

**Comment by craigraw** [comment]
Is your Sparrow connected? What does the toggle in the lower right corner indicate? Is it yellow, green or blue?

**Comment by patrxck1** [comment]
It’s yellow when on.

**Comment by craigraw** [comment]
Ok. Refresh the wallet (View menu) and check the loading log (Transactions tab) to make sure there are no failures loading the wallet. Also, check the Address above appears in the Addresses tab.

**Comment by patrxck1** [comment]
I did all of that and nothing shows up in transactions and none of my
receive addresses match the one it gives me. I still don't understand why
when I copy my receive address, no matter what it is, it copies
"38pBm8pU2KkkBeCczLhTwXRCXD3W91Jha4". I even made a new wallet and that one
copies the address perfectly fine.

**Comment by craigraw** [comment]
You mean no matter what the address says on the screen, it copies "38pBm8pU2KkkBeCczLhTwXRCXD3W91Jha4"? Given this is a legacy wallet, I assume your addresses start with "`1....`"? Was the new wallet that you created also a legacy wallet?

**Comment by patrxck1** [comment]
Yes correct. The new one I made was a native segwit and it copies the
address just fine.

**Comment by craigraw** [comment]
Unfortunately, it sounds like the machine Sparrow is running on may be compromised. I suspect there is malware running which monitors the system clipboard for any legacy Bitcoin addresses, and replaces them with its own address. If you take a look at https://mempool.space/address/38pBm8pU2KkkBeCczLhTwXRCXD3W91Jha4, you will see that address has been reused in many transactions. One form of this malware is known as 'CryptoShuffler', although there may be others.

It appears that the malware does not operate on Native Segwit addresses - that's why you were able to copy the address from your new wallet without issues.

**Comment by patrxck1** [comment]
I was thinking that when it first happened and once I ran malwarebytes, the
address copied just fine. Thank you

**Comment by craigraw** [comment]
Glad it's resolved.
