### ISSUE TITLE
PSBT error

### ISSUE THREAD

**Issue by Paul8562** [sparrowwallet/sparrow#461]
Cant sign multi-sig , just get multi-sig PSBT error 927 on coldcard.

**Comment by craigraw** [comment]
This error is caused because the multisig wallet saved on the Coldcard is not the same as that in Sparrow: https://github.com/Coldcard/firmware/blob/322c6e669c19421e77acc8eddb9d6623faaffe34/shared/multisig.py#L927

I would suggest deleting whatever multisig wallets have been saved to the Coldcard and re-exporting the Coldcard multisig setup (a .txt file) containing the multisig details from Sparrow. It is also possible to disable the check using the 'Trust PSBT?' setting on the Coldcard, but this is not recommended in general.
