### ISSUE TITLE
Transaction opens in wrong window w/ similarly defined MS wallets 

### ISSUE THREAD

**Issue by Francisco-DAnconia** [sparrowwallet/sparrow#467]
This was strange and unlikely to be a real world problem. I was experimenting with keystore permutations registering XPUBs and signing . On macOS 12.2, Sparrow 1.5.6 using a Coldcard (4.1.3) & Trezor.

1. Menu Item "Open Wallets in New Windows" - ON
2. Crate a sparrow multisig wallets with the following 2 keystores [CC + Trz]
3. Crate a sparrow multisig wallets with the following 2 keystores [Trz + CC] (just reverse the registration of the keystores)

This are treated as identical wallets to Sparrow (the same Output Descriptors). Interestingly Coldcard allows you to register both, but warns of the similarity and will sign w/o errors as long as at least MS wallet is registered.

4. Create a transaction in the second sparrow wallet opened (e.g. [Trz + CC]). 
5. Click Create Transaction. The transaction opens as a tab in the other Sparrow wallet window ([CC + Trz]). 

I'm not sure if this is indicative of a more general bug, or just something that might occur in this admittedly weird testing scenario. FWIW.

**Comment by craigraw** [comment]
As you've noted, these wallets are equivalent (technically due to BIP67). Sparrow must be able to open a PSBT from it's File menu and find the best wallet window to open it in. In this case, both windows are equivalent, so it's an unusual edge case to open it in the window you weren't expecting, but not really a bug either IMO.
