### ISSUE TITLE
Gap limits for post mix seem arbitrary and large.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#490]
I can't recall having changed those setting aside from trying to reduce the Watch Addresses.

On one of my wallet I have:

<img alt="image" src="https://user-images.githubusercontent.com/388716/160527271-f094cdba-36c3-482a-b1a8-be8381ef1ebe.png">

Isn't gap limit 1396, the amount of unused addresses that will be checked?
Minimum is 5000

Other wallet: (also postmix)
<img alt="image" src="https://user-images.githubusercontent.com/388716/160527491-e6656b6b-834a-4f3c-8522-ce672a884536.png">

more reasonable even though I'd expect a static gap limit in the 50-100 range.

Update:
Changing the gap limit to 99 is letting me change the watched address to 100

**Comment by Transisto** [comment]
From what I understood if 3000 address have been with a gap limit of 100 and a Watch last of 500
only address 2500 to 3100 will be monitored.

**Comment by craigraw** [comment]
The gap limit has been increased because the Whirlpool co-ordinator will not accept addresses it has seen before, so the client needs to send another unused address. This can increase the necessary gap limit, so Sparrow increases the gap limit setting automatically.

In your case, I suspect that server connectivity issues are to blame for these extensive gap limits.

> From what I understood if 3000 addresses have been used so far with a gap limit of 100 and a Watch last of 500
only address 2500 to 3100 will be monitored.

This sounds correct.
