### ISSUE TITLE
Label is required when sending

### ISSUE THREAD

**Issue by sgeisler** [sparrowwallet/sparrow#5]
I don't know if this is intentional, but requiring a label for outgoing transactions is rather annoying (even though it might be beneficial if you need to do accounting).

![2020-09-04-001109_5120x1440_scrot](https://user-images.githubusercontent.com/1876998/92178850-c8f5e880-ee43-11ea-99af-d9fa5824b242.png)

**Comment by craigraw** [comment]
It is intentional - the thinking is that even though it takes a little extra effort it really adds to the richness of the data down the line given how the label is applied not only to the transaction, but it's TXIs and TXOs. From a privacy POV it can be important to know which UTXOs to spend given what their history may reveal, and it's really difficult to keep track of change without labelling.
