### ISSUE TITLE
Add address book feature

### ISSUE THREAD

**Issue by chrisrico** [sparrowwallet/sparrow#511]
I've recently switched from Electrum to Sparrow, and I absolutely ***love it***. There's only one feature I'm missing (other than #147), which is an address book. Some people reuse addresses no matter how often I tell them they shouldn't and it would be great to have an address book similar to Electrum's. Just a simple name, address key value pair.

It would be fantastic if the "Pay to" field had a name based auto-fill.

Extra bonus points if you can add a descriptor instead of a single address, and when used, looks up the first unused address for that descriptor.

**Comment by craigraw** [comment]
It's highly unlikely this would ever be introduced, since it would encourage address reuse which is unconditionally bad. But the answer here is to use PayNyms/payment codes. This is an address book of other wallets already built into Sparrow, where private addresses can generated independently for linked PayNyms. See the docs on "Spending Privately" for more info.
