### ISSUE TITLE
Building on Windows 10 results in BUILD FAILED error.

### ISSUE THREAD

**Issue by hugoender** [sparrowwallet/sparrow#534]
Followed instructions on main page for building in Windows but after sending `gradlew jpackage` I get a `BUILD FAILED` error. Screenshot below.

![image](https://user-images.githubusercontent.com/6217175/166174344-dd10dde6-b65f-442b-b933-77b5fe67e67e.png)

Checked Java version and it seems correct.
![image](https://user-images.githubusercontent.com/6217175/166174369-83131fea-8333-494f-990e-753b4632fb1d.png)

Any help with this would be greatly appreciated. Must be something stupid I'm doing wrong since I can't find any record of anyone else having this issue.

**Comment by craigraw** [comment]
I suspect the original cause of this issue was a misconfigured `JAVA_HOME` environment variable, pointing to an older version of Java. When you used 

> gradlew jpackage -Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot"

you effectively overided the environment variable. See https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties for more detail on this.

**Comment by hugoender** [comment]
Configuring  `JAVA_HOME` to point to 16.0.1.9 in my Environment Variables was the first thing I did and it actually didn't solve the problem. It wasn't until I sent `gradlew jpackage -Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot"` that it actually was able to build the binaries. 

At that point I then ran into a new error as shown below:
![image](https://user-images.githubusercontent.com/6217175/166610263-960f24eb-8f82-479c-b763-1aa1d8e797e1.png)

From my chat with you, @craigraw, on Telegram I was made aware that this new error just meant the installer wasn't built and that I needed to download the WiX Toolset to proceed with building the installer.

Since the binaries were built, I decided to forego installing yet another set of tools that I wasn't familiar with and chose to just compare the binaries that had been built with the binaries that are provided on the Sparrow website for download. Alas, this resulted in a hash/checksum difference. Since at this point this has now diverted into a separate issue I'll end the discussion about this here. 

All of that said, I believe closing this issue without first addressing it by at the very least updating the Build Instructions is a bit premature. I'm sure I'm not the only one with this issue.

**Comment by craigraw** [comment]
If it wasn't `JAVA_HOME`, then I suspect that there is a `gradle.properties` file from a previous build being referenced from your home folder or somewhere similar (the link above should help determine). What is fairly certain is that there was an older version of Java being referenced from Gradle, and the manual override flag should not generally be necessary.

> All of that said, I believe closing this issue without first addressing it by at the very least updating the Build Instructions to at least include a note about the Environment variable and/or the Gradle flag command to set the proper path is a bit premature. I'm sure I'm not the only one with this issue.

Let's see if anyone else reports this issue - first time I've encountered it. It would be helpful if you could determine the actual cause (how the older version of Java was being referenced). I closed the issue simply because you had already solved it :)

**Comment by craigraw** [comment]
> From my chat with you, @craigraw, on Telegram I was made aware that this new error just meant the installer wasn't built and that I needed to download the WiX Toolset to proceed with building the installer.

A note about WiX was added to the build instructions in 631f5d48.
