### ISSUE TITLE
Signature status missing in offline-mode

### ISSUE THREAD

**Issue by pvig0q1s** [sparrowwallet/sparrow#549]
Sparrow 1.6.3

When loading a transaction into Sparrow (while connected to a server) signature status in the shape of a progress bar is shown (plus the two buttons)
![sparrow-1](https://user-images.githubusercontent.com/77514744/168895448-c918aa22-8b00-4f0e-bc01-5c7ff20d89bb.jpg)

When disconnecting the "Broadcast Transaction"-Button changes to "Save Final Transaction"-Button
![sparrow-2](https://user-images.githubusercontent.com/77514744/168895465-38c6075b-a1a4-42ac-8ac7-6b1bdc3d1779.jpg)

Meanwhile, when loading a signed Transaction in offline-mode there is no progress bar in the UI
![sparrow-3](https://user-images.githubusercontent.com/77514744/168895476-9eac9011-1dbe-411f-9ceb-3de99cbfac0f.jpg)

Is there a specific reason the progress bar (while in offline-mode) isn't shown? 

If a corresponding wallet is not opened, the same behaviour while in a connected state (with non-opened wallet) could be applied -> label the progress bars 'Keystore X'

**Comment by craigraw** [comment]
I agree, this behaviour has been improved in 82be3a5 to show the signature status for loaded transactions even when offline. It required a little extra thought, since when Sparrow is taken online there must be an attempt to determine if it has already been broadcast, and to update the display if it has.
