### ISSUE TITLE
Stuck waiting for "Connecting to server, please wait..."

### ISSUE THREAD

**Issue by alevchuk** [sparrowwallet/sparrow#587]
Context:
In Preferences -> Server, I'm trying to change configuration of my server (bitcoin node is up but the auth is not correct).

Problem:
All the buttons are grayed-out (not clickable). Seem I have to wait for 10 minutes+  (forever?) for the connection attempt to time out. Long enough to fill out this issue.

Workarounds?
Can't find any. Turing off network does not help.

Versions:
I have Bitcoin Core version v23.0 and Sparrow 5da9532614a67a207ac5b3f197913a8cb1214c1a (earlier version of Sparrow had that issue too).

Screenshot:
![Screenshot from 2022-06-03 08-53-55](https://user-images.githubusercontent.com/64738/171903971-53b4408c-1997-487d-af95-5696085f537c.png)

**Comment by Bzvwf16WSDKoSZd8** [comment]
I sometimes encounter this situation too. I think sparrow did not set the "timeout" parameter for network requests.

In the case of a normal network request, if no response is received after 5 seconds, it should be considered invalid and the request should be retried or cancelled.

At the very least, the user should be informed of the status of the request, such as "timeout", "retry", "cancel".

If only "Connecting to server, please wait..."is displayed for a long time, the user does not know if the connection is successful or unsuccessful.

**Comment by craigraw** [comment]
> I think sparrow did not set the "timeout" parameter for network requests.

Sparrow actually does set the timeout parameter, asking the BWT library to perform a socket timeout after 30 seconds when using the 'Test Connection' button. I've just tested this against a firewall set to drop packets, and Sparrow did indicate a failure to connect after 30 seconds had elapsed.

However, Sparrow does not set a socket timeout parameter in BWT when connecting to Bitcoin Core outside of 'Test Connection'. This is because the timeout parameter applies to read and write timeouts as well, and typically it can take many minutes or even hours to import and scan addresses in a new wallet, especially when the birth date has been set many years back. The read timeout here causes BWT to timeout waiting for Bitcoin Core to do this, resulting in a failure of the wallet import. 

(That said, I was actually unable to recreate the described behaviour, getting an OS-level socket connection timeout even when connecting outside of 'Test Connection'. I suspect this is due to network level configuration. )

I believe this issue can be resolved by allowing Sparrow to set a separate socket connect timeout (apart from the read timeout) so that both situations can be handled. I have added an issue for this: https://github.com/bwt-dev/bwt/issues/99

**Comment by craigraw** [comment]
> Can I modify a config file directly to remove the problematic server connection?

Sparrow's config is available in the Sparrow home folder - see the `config` file - and can edited in a text editor.

**Comment by craigraw** [comment]
While it seems unlikely that BWT will be updated to fix this, Sparrow v1.7.2 was released with a new Core <-> Electrum server implementation called Cormorant that will be used if the version of Bitcoin Core >= 24. A connection timeout of around 5 seconds is used.

I'm closing this off, it's probably as resolved now as it's ever going to be.
