### ISSUE TITLE
Import from Electrum seed?

### ISSUE THREAD

**Issue by HardCorePawn** [sparrowwallet/sparrow#59]
I see that Sparrow now supports importing from Electrum wallet files... are you planning on implementing the ability to create a wallet from an Electrum Seed phrase?

**Comment by craigraw** [comment]
Although it would be relatively simple to implement (as you note, Sparrow already supports the Electrum seed format internally), I've held off on doing so because:

- it might be confusing to have two types of seed lists to choose from
- I'm not sure it's a good idea to keep supporting such an isolated 'standard'

Thoughts?

**Comment by 2pac1** [comment]
Creating confusing with that might not be best. 
And you want to have everything standardised.
Not aware of who else is using that Electurm seed standard? 

Can you import it to any hardware wallet? Don't think so, because it is not widely accepted as standard.

**Comment by craigraw** [comment]
Thanks, I agree. I believe only the Electrum client supports it.

**Comment by 6102bitcoin** [comment]
Outstanding Action: Propose issue is Closed
Proposed Priority: NA

**Comment by craigraw** [comment]
Agree, closing this off.
