### ISSUE TITLE
blockchain.scripthash.get_history call to Electrs is inefficient 

### ISSUE THREAD

**Issue by alevchuk** [sparrowwallet/sparrow#593]
Electris logs: 

```
electrs::electrum] your wallet uses less efficient method of querying electrs, consider contacting the developer of your wallet. Reason: blockchain.scripthash
.get_history called for unsubscribed scripthash: 123abc
```
when looking up transactions.

Details on how to reproduce in electrs issue romanz/electrs#724

Also, if we can avoid calling this API from Sparrow than this will resolve a privacy leak where a scripthash is stored in logs. See above mentioned issue for details.

**Comment by craigraw** [comment]
Although there is nothing in the Electrum specification to suggest that one should subscribe a script hash before querying its history, Sparrow does not do this unless requesting the history for a transaction outside of a wallet. This is generally infrequent, and performance matters less in this case.

I think the simplest solution here is to fix the log message in Electrs (at least) rather than burden the server (and thereafter the client) with unnecessary script hash subscriptions.
