### ISSUE TITLE
Tools = > Sweep Private Key Icon greyed

### ISSUE THREAD

**Issue by TEST100077** [sparrowwallet/sparrow#595]
Hello

I am trying to sweep a private key into Sparrow wallet but it seems the icon is greyed in the section Tools 
= > Sweep Private Key Icon greyed

thanks a lot

**Comment by sutterseba** [comment]
_Sweep Private Key_ is greyed out while disconnected. Have you checked your server configuration?

**Comment by TEST100077** [comment]
Thank you for your reply Sebastian.

Yes if online I am able to connect to Emzy Server and the field is not greyed... 

However I do not mean to do that but rather the setting below instead so as to minimize attack surface.

The setting is on 2 desktops and no hardware wallets come into play.

1/ DESKTOP 1 HOT WALLET . being Sparrow WATCH ONLY wallet via the Public Key Xpub or Zpub taken from the air gapped Desktop 2 . This Hot Wallet is meant to be connected to Emzy Server or Bitcoin Core via a PSBT file.

2/ DESKTOP 2 COLD WALLET.  being Sparrow Air Gapped Wallet dedicated to Signing PSBT files that are later fed into Desktop 1 for spending.
I would like to import or rather SWEEP a paper wallet into Desktop 2 that is NEVER connected to internet.
In this case the field is greyed and I am not allowed to do this... contrary to ELECTRUM wallets set in TAILS

I hope it is clear for you

thanks for helping
Regards

**Comment by craigraw** [comment]
The reason Sparrow requires you to be connected is because it needs to search for UTXOs connected to the private key you enter. It can then construct a transaction with these UTXOs as inputs, allowing Sparrow to sweep those funds into the provided address by broadcasting the constructed transaction. 

It would also technically be possible to retrieve the UTXOs from the public key derived from the private key (which would be a new feature) but I'm not sure that Electrum supports that?

**Comment by TEST100077** [comment]
Hi Craigraw

If you run the link below 
[https://www.youtube.com/watch?v=ixnTZDZ0-yk](url)

Crypto Guide explains in depth what I need at the following time frames + you can see enclosed the set up.

5 minutes 00 sec for the air gapped device or a laptop.

thank you

![How to sweep a private key using Electrum Air Gapped](https://user-images.githubusercontent.com/107300893/175060056-a7e082ac-2246-4f76-ba99-622280fa2256.png)

**Comment by craigraw** [comment]
I understand the use case. Unfortunately, Sparrow does not support wallets with single keys, which are required to support this use case. Supporting single key wallets would add significant complexity to the codebase, which I don't feel is justified by their relatively rare use these days. 

The functionality to sweep a private key does not create a wallet, but rather finds any available UTXOs from the connected server, signs them with the private key and broadcasts the resulting transaction. Since all funds associated with a private key get immediately spent using this tool, the risk of entering the private key into an internet connected computer is certainly reduced (although not I'll grant completely eliminated).

**Comment by craigraw** [comment]
Closing this off as unsupported.
