### ISSUE TITLE
[Bug] Whirlpool "Waiting for prodcast" loading bar misplaced

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#597]
# Description 

In the UTXO tab, once a whirlpool remix gets accepted Sparrow jumps to the next utxo and the loading bar there increases to "Registered input". 

In addition there is now a second loading bar for that pool size which states "Waiting for broadcast of transactionID:outputNumber" which correlates with the unconfirmed transactionID:outputNumber of the remix. The loading bar is at the wrong place though, see number 2 at the provided screenshot. I can't give you advice about the nature of transaction where the loading bar is falsely placed (e.g. if this it the previous registered one or something else)

![Sparrow_2_1](https://user-images.githubusercontent.com/72392544/173366017-19481759-6380-4644-8474-bee96a45d080.png)

**Comment by craigraw** [comment]
I believe this is actually due to a server issue. When a mix transaction happens, the server needs to notify Sparrow of changes on two addresses (technically [script hashes](https://electrumx.readthedocs.io/en/latest/protocol-basics.html#script-hashes)):
1. The script hash status on the address that the previous (now spent) UTXO has changed
2. The script hash status on the address with the new UTXO has changed

These are independent updates that the server sends, and if it only sends one (the second in your case) then the situation you have described can occur, where Sparrow has no knowledge that the previous UTXO has been spent. Generally Electrs suffers from incomplete script hash notifications. It's worth noting that Sparrow includes code to manually check all related script hashes when it knows the transaction, but that is not true in this case.

The correct solution here is to fix the server - this should not occur for example when using Fulcrum.
