### ISSUE TITLE
Scanning 3of5 QR code with CoboVault and Specter-DIY HWWs fails.

### ISSUE THREAD

**Issue by dermichal** [sparrowwallet/sparrow#60]
Succesfully exported a 3 of 5 Multisig-Wallet from Specter-Desktop into Sparrow. 

When trying to sign a transaction with CoboVault the following error appears:
![IMG_2374](https://user-images.githubusercontent.com/688962/106962934-20281e00-6740-11eb-804c-5f540a340c92.JPG)

Scanning with Specter-DIY HWW also fails:
![IMG_2375](https://user-images.githubusercontent.com/688962/106962999-3df58300-6740-11eb-9f02-709e069f94a2.JPG)

Both devices are able to read 3of5 QR from Specter-Desktop and BlueWallet.

Thanks

Firmware:
Cobo: V2.3.1-BTC_Only
Specter-DIY: v1.4.5

**Comment by craigraw** [comment]
On Sparrow, did you enable the legacy mode (button at the bottom of the QR display dialog)?

**Comment by dermichal** [comment]
Do you mean the type of Sighash? Tried all of them. Unfortunately it makes no difference.

**Comment by craigraw** [comment]
No - there is a button at the bottom of the dialog where the animated QR is displayed.

**Comment by dermichal** [comment]
No button present in my QR dialog.
<img width="559" alt="Screenshot 2021-02-07 at 18 51 41" src="https://user-images.githubusercontent.com/688962/107154934-dcb6f500-6975-11eb-90d6-ab9a136c9916.png">

Running Sparrow 1.0.0

**Comment by craigraw** [comment]
Ok - because this was an import, the keystore for the Cobo Vault was imported with the essential public key details, but not the device type. Currently, Sparrow only displays the legacy mode button when a Cobo device type is part of the wallet. Possibly this should change!

In the meantime, the simplest way to solve this is to replace that keystore in your wallet settings, reimporting the Cobo. To do this, go to the Settings tab, and select the keystore that represents your Cobo (or each of them in turn if there is more than one). Click 'Replace', select Airgapped in the dialog that pops up, and reimport the Cobo details by selecting the Scan button on the Cobo Vault type, and presenting the QR on the device using the Multisig Wallet > Show/Export XPUB feature. 

The button should then be present in the QR display dialog.

**Comment by craigraw** [comment]
Added the legacy QR display button for imported wallets in 0097a1e.
