### ISSUE TITLE
[Bug] BIP39 wallet with passphrase should not accept blank on re-enter the BIP39 passphrase window

### ISSUE THREAD

**Issue by tadeubas** [sparrowwallet/sparrow#603]
When Sparrow asks to Re-enter the BIP39 passphrase, it should not accept blank! Otherwise when you click on `Settings > Keystores > View Seed...` you will see the text _"Passphrase entered"_ but the wallet will be the same as a _"No passphrase"_ causing misunderstanding to the user.

Also the text of BIP39 passphrase window should always be the same _"Re-enter"_, and not the _"Enter"_ txt that apeears when you open Sparrow with an imported wallet loaded... also, none of them should accept a blank password.

![image](https://user-images.githubusercontent.com/5518496/174442498-0b764d5c-800a-4e0d-97f4-9bb76e626ceb.png)

![image](https://user-images.githubusercontent.com/5518496/174442941-5cd5ab76-6646-4f46-8db8-2e2fc8342dec.png)

![image](https://user-images.githubusercontent.com/5518496/174442749-92b04e20-437f-4e8d-8716-cd3ff568b03b.png)

![image](https://user-images.githubusercontent.com/5518496/174442760-e25db05d-7e60-4f39-ab9d-90ceac51aa97.png)

Sparrow `1.6.5`

**Comment by sutterseba** [comment]
Not sure what you mean. When opening a wallet file, you're only asked once for the passphrase. Leaving blank here is perfectly fine and actually part of the whole idea (e.g. plausible deniability).

When importing a new keystore, you're asked for the passphrase twice and you'll receive an error if the phrases do not match, including your case of leaving it blank the second time. I tried reproducing this on MacOS and Win 10.

<img width="459" alt="Screenshot 2022-06-18 at 21 29 18" src="https://user-images.githubusercontent.com/79049748/174454857-5a58836d-5b02-4844-b46f-56df76ccc99d.png">

I agree that _Passphrase entered_ may seem confusing if you didn't even enter one. But the user should still be able to see that he was prompted for a passphrase and that the feature is enabled for the current keystore. Maybe changing this to _Passphrase enabled but left blank_ would be best.

**Comment by tadeubas** [comment]
You forgot the scenario from `File > Import Wallet...`, because in this scenario the Sparrow first asks for a Wallet password, then it asks for the BIP39 passphrase. The scenario you tested it asks for the BIP39 passphrase right away and give a feedback if it doesn't match.

![image](https://user-images.githubusercontent.com/5518496/174456637-1eef0625-3bd2-4c01-b67e-3d6e7592db0e.png)

The problem is that the passphrase must be required if the user informed that the wallet has a passphrase. You can type anything to plausible deniability and at the same time avoid the user confusion with the password of the wallet.

**Comment by sutterseba** [comment]
Oh, now I understand! That is certainly a bug and even potentially dangerous because if a user misspells his passphrase this way (the second time) he will not be aware of his mistake and may send funds to the wrong wallet.

The re-enter prompt is basically completely missing here since the "second" prompt is just the default prompt as if you were regularly opening the wallet file.

**Comment by tadeubas** [comment]
@Bzvwf16WSDKoSZd8 I disagree with your solution because it removes the possibility of a plausible deniability, unless if implemented another way, like using the wallet password (BlueWallet has an app password to do plausible deniability).

Now I wondered what Sparrow does when it is closed and I was using a wallet with a BIP39 passphrase... It only saves the wallet seed encrypted and then constructs the wallet with passphrase everytime in memory only when the user types the BIP39 passphrase?

**Comment by sutterseba** [comment]
> The wallet is still encrypted using the wallet password.

But the whole point of an optional passphrase is to act as a second factor and/or plausible deniability, which as @tadeubas already explained, would be mitigated. Software or hardware wallets should not remember your passphrase, that's part of the use case, unless you specifically want it to (e.g. Ledger Attach to PIN).

**Comment by Bzvwf16WSDKoSZd8** [comment]
@tadeubas Look at this reddit post.
[https://www.reddit.com/r/Bitcoin/comments/tpr446/psa_be_extremely_careful_when_entering_your/](url)

The user mistyping BIP39 passphrase seems to be the bigger problem than the plausible deniability at the moment.
Some the other wide used bitcoin wallet, such as blue wallet, also just need user ether BIP39 passphrase once when import.

BIP39 Wallet haven't store any passphrase in plain-text. It just store the 512 bit HD seed.
This is the code from the BIP39 Reference Implementation

```python
    def to_seed(cls, mnemonic: str, passphrase: str = "") -> bytes:
        mnemonic = cls.normalize_string(mnemonic)
        passphrase = cls.normalize_string(passphrase)
        passphrase = "mnemonic" + passphrase
        mnemonic_bytes = mnemonic.encode("utf-8")
        passphrase_bytes = passphrase.encode("utf-8")
        stretched = hashlib.pbkdf2_hmac(
            "sha512", mnemonic_bytes, passphrase_bytes, PBKDF2_ROUNDS
        )
        return stretched[:64]
```

The plausible deniability using BIP39 passphrase when wallet open should be disable by default and only enable manually by user.

On my solution, I suggest "user need to type twice of the BIP39 passphrase when wallet import as same as the of the wallet encrypt password setting scheme to reducing the chances of user mistyping.

**Comment by tadeubas** [comment]
@Bzvwf16WSDKoSZd8 Thx to let us known these users cases... I opened this issue because I was also confused about the way Sparrow deals with the BIP39 passphrase via `Import Wallet...` functionality. I didn't know that Sparrow had plausible deniability until @sutterseba said that to me on this issue... but now I see that the plausible deniability is implemented in various ways and the way currently employed by Sparrow is creating some misunderstandings to the users, and unfortunately some of them are losing sats because of the way the functionality is implemented.

I think the solution is up to the Sparrow main developer to decide, but definitely the way Sparrow implemented BIP39 passphrase and plausible deniability with this passphrase is causing issues with the users... maybe plausible deniability should be implemented with the wallet password only, or BIP39 passphrase must always be typed twice to avoid mistakes? Also would be good to have an eye icon to "show/hide the password" like we see on phones... anyway, thx for letting us know these issues

@craigraw what do you think would be the best way to solve this issue with BIP39 passphrase mistyping?

**Comment by craigraw** [comment]
With respect to using BIP39 passphrases on Sparrow, the current design maximises security (at the expense of, for example, telling the user they have entered an incorrect passphrase). Unfortunately there is no perfect solution here.

First off, it makes no sense at all to store the passphrase in the wallet file. In that case it simply acts as a 25th word, and 24 words already provide more than sufficient entropy. The point of the passphrase is to create the well known "something I have + something I know" security paradigm. In this case, the wallet file is something you have, and the passphrase is something you know. So let's put that aside.

Secondly, there is an argument that Sparrow should store something derived from the passphrase (not the passphrase itself). For example, Sparrow could store the master fingerprint of the seed (derived from the BIP39 words + passphrase) which is a 4 byte value that should (with some rare collisions) identify whether an entered passphrase is correct. But there is a significant cost to doing so in reducing security by making a brute force attack easier. 

To explain further, a Sparrow Wallet *.mv.db file stores nothing derived from the passphrase. This means that if the wallet file is decrypted, a brute force attack to locate any funds must not only calculate the seed from the BIP39 words + passphrase, but also calculate addresses and search for any funds on the blockchain. The first part of this (deriving the seed) is computationally inexpensive, since BIP39 uses the PBKDF2 algorithm which is now very old and simple to execute, even with the prescribed 2048 rounds. (By the way, [this is a issue](https://togithub.com/spesmilo/electrum/issues/3147) with Electrum's wallet file encryption, but I digress). If Sparrow stored the derived master fingerprint in the wallet file, then a brute force attack could simply iterate passphrase guesses until it found one that matched the master fingerprint. Without this information however, it also needs to (at least) generate the first address and search the entire blockchain for a transaction output to it. This is not only computationally much more expensive, but also scales as the blockchain grows, giving some protection as computing resources inevitably become cheaper and brute force attacks become easier over time.

Although Sparrow does not have the information to tell you if you have entered an incorrect passphrase, it can see if, on loading a wallet, the retrieved transaction history is entirely different from that stored in the wallet file. If it detects this, it does a full refresh of the wallet, discarding all stored transaction history and loading everything from the server again. So if you enter an incorrect passphrase, you will be presented with an empty wallet as soon as the refresh begins. This speaks somewhat to plausible deniability, but really is just the best Sparrow can do given it is maximising security over other aspects of passphrase use.

The question you need to ask yourself is whether you are prepared to give up security for UX - which is a difficult question to answer in general, since it ultimately depends on the amount of entropy contained in a given passphrase.

**Comment by tadeubas** [comment]
@craigraw thx a lot for the explanations! Without changing the way Sparrow works, which is awesome, I think that asking for the user to always type twice the BIP39 passphrase is enough (so Sparrow UI only check if the user typed 2 times the same passphrase, otherwise asks to type the passphrase the first and second time again). This would avoid mistyping by the user (the [Reddit ](https://www.reddit.com/r/Bitcoin/comments/tpr446/psa_be_extremely_careful_when_entering_your/) showed 2 users that lost funds because of mistyping). Also an eye option to click (show/hide) the password the user is typing would be great to avoid mistyping, this without not compromise the Sparrow security neither plausible deniability  because it is just an UI change. What do you think?

**Comment by Bzvwf16WSDKoSZd8** [comment]
@craigraw But Sparrow already using a strong encryption "Argon2" (winner of the Password Hashing Competition in 2015), The situation you mentioneds unlikely to happen when the user provides a strong password.

I strongly agree that security is very important, but also to strike a balance between user experience.
I think currenyly have two mainly types of bitcoin wallet user.

1) Users who have a huge amount of bitcoin.
2) Users who "NOT" have a huge amount of bitcoin.

For case 1) 
This type of user may use Sparrow wallet only as watch-only wallet.  They will storing their seed (metal backup) and signing their transaction (*.psbt) "air-gapped" using their own hardware wallet (coldcard, passport, trezor...) rather then just using Sparrow wallet.

For case 2) 
This type of users may use Sparrow wallet only as hot wallet with daily spending.  They need a smooth user experience than the extreme level the security, They still have a option to setting a wallet password secure their wallet using sparrow wallet strong encryption "Argon2".

The user need to typing BIP39 passphrase on Sparrow wallet is obviously the second type of user.

**Comment by craigraw** [comment]
I given this a lot of thought, and ultimately I don't want to reduce Sparrow's potential security for ease of use. Many users may store significant amounts in software wallets (especially those using Whirlpool) and not everyone can afford hardware wallets. Further, a common security practice is "defence in depth" which in this case suggests one might choose to not rely not on the wallet password alone. Ultimately, it's a choice I don't want to take away from the user.

With respect to the OP's points, Sparrow is here asking for the passphrase as per the normal wallet load sequence, which it uses even when importing from a seed. I'll need to see whether it makes sense to complicate the load process to handle this special case. I agree the password dialog should not accept an empty password, and reflecting an empty passphrase with a "No passphrase" message on the seed view dialog seems a reasonable improvement.

**Comment by Bzvwf16WSDKoSZd8** [comment]
@craigraw I agree with you, but why Sparrow's giving users a choice of not enabling wallet encrytion, but not giving users a choice of not enabling the BIP39 passphrase plausible deniability?

**Comment by craigraw** [comment]
Yes, they are related to security, but otherwise not closely related. It is really just a convenience factor that causes some wallets to conflate passwords and passphrases.

Passphrase plausible deniability is difficult to support well given the above considerations (Sparrow must receive a response from the server before it can refresh the wallet). That said, it is simple enough to achieve some form of it by just using two passphrases. Adding a further layer of configuration for no passphrase wallets to optionally request a passphrase will further complicate things, and I'm not sure this would materially improve things.

**Comment by craigraw** [comment]
As of 90224383:
1. Password field cannot be empty on encrypted wallet load
2. The passphrase will not be re-requested on importing a BIP39 wallet
3. Empty passphrases will be shown as "No Passphrase" in the seed view dialog
