### ISSUE TITLE
Labels on addresses incorrectly applied to wallets with different passphrases

### ISSUE THREAD

**Issue by LightningSats** [sparrowwallet/sparrow#628]
If you apply a label to an address in a wallet with a passphrase but use the same ".mv.db" file for another wallet without the passphrase, or a different passphrase, the label will carry over to the other wallet and be applied to the addresses in the same index position as the wallet where the label was originally applied.

**Comment by craigraw** [comment]
This is expected behaviour. In order to maximize the additional security provided by your passphrase, Sparrow stores nothing derived from it. This means it cannot know if you have entered a different passphrase. This might seem inconvenient, but it makes the wallet significantly more difficult to brute force. 

The solution to using different passphrases is simply to use different wallets for each passphrase.
