### ISSUE TITLE
ConcurrentModificationException when opening wallet

### ISSUE THREAD

**Issue by ghost** [sparrowwallet/sparrow#643]
Post 1.6.6 update I have encountered an issue when attempting to open a specific wallet file. 
After decrypting the file with the wallet password, I get an error message pop-up after entering my passphrase saying "Error Opening Wallet". 
Clicking ok takes me to my unlocked wallet where everything except my post-mix wallet is open.
From what I can see this is only effecting a single wallet file.

After 7-8 attempts the wallet finally unlocked however, closing & reopening the file again reproduced the same issue.

>ERROR [JavaFX Application Thread] c.s.s.AppController [null:-1] Error opening wallet
java.util.ConcurrentModificationException: null

**Comment by craigraw** [comment]
Thanks for the report. Unfortunately this is not a particularly helpful error in the logs. I assume nothing else is written to the log when the error occurs? It might be worthwhile to cut and paste a broader area from the log file just to be sure. 

Otherwise, the best way to track this down would be to run from source, which should provide more logging. Doing so is not particularly difficult. Unless you have another way of installing Java 18, I suggest running on the command line (I assume you are using Linux):

```
curl -s "https://get.sdkman.io" | bash
```

to install it SDKman, which is a useful package manager. Then in a new terminal:

```
sdk install java 18.0.1-tem
GIT_TAG="1.6.6"
git clone --recursive --branch "${GIT_TAG}" https://github.com/sparrowwallet/sparrow.git
cd sparrow
./sparrow
```

This will run Sparrow from source. When you open that wallet file again, you should see a more comprehensive error printed to the terminal.
