### ISSUE TITLE
Mixing to another wallet does not work if the UTXO already has more than the minimum mixes

### ISSUE THREAD

**Issue by MarcelRobitaille** [sparrowwallet/sparrow#649]
I am using the whirlpool mixing for some UTXOs. After they went through some mixes, I started mixing to another wallet. I set a minimum mix number of 5. The UTXOs below 5 mixes are successfully sent to the new wallet on the fifth mix. However, I had a UTXO that already had 6 mixes. It now has 8 mixes but has not been sent to the second wallet.

Steps to reproduce:
1. Start a whirlpool coinjoin
2. Wait for one UTXO to get 6 mixes
3. Set up mixing to a second wallet

I am using Sparrow 1.6.5.

**Comment by RequestPrivacy** [comment]
Not sure if this is a bug.

Have you considered that according to the [docs](https://sparrowwallet.com/docs/mixing-whirlpool.html#mixing-to-cold-storage) there is only a 75% chance that it will mix to your specified wallet after reaching the threshold?

This is a protection, because always mixing out after a fixed number of mixes could de-anonymize your utxos as belonging to the some entity.

**Comment by craigraw** [comment]
@RequestPrivacy is correct, there is a 75% chance of mixing out after the threshold has been reached. The current number of mixes are always considered when selecting the next address to mix to, not just at the threshold number of mixes.
