### ISSUE TITLE
Remove all mentions that Sparrow is reproducible

### ISSUE THREAD

**Issue by nyxnor** [sparrowwallet/sparrow#672]
Sparrow is not reproducible, it is just aiming to be.
#192
#197 
#619

The builds on bitcoinbinary.org is misleading. It should not be trusted, it does not even run the diff, it just builds the package https://github.com/coinkite/bitcoinbinary.org/raw/main/sparrow/sparrow-1.6.6-video.webm

The latest change that was made in the regards to reproducibility according to https://github.com/sparrowwallet/sparrow/issues/619#issuecomment-120930484 is on your beta repository, not on this one, but still not reproducible.

It misleads users to believe that is reproducible when it clearly is not.
I'm not attacking your efforts to make it reproducible, I'm attacking the claim that is reproducible.

The claims should be removed from the site, the readme, and the doc/Reproducible.md.

**Comment by nyxnor** [comment]
https://github.com/sparrowwallet/sparrow/issues/192#issuecomment-1228636423

**Comment by craigraw** [comment]
> on your beta repository, not on this one, but still not reproducible.

Yet you did manage to reproduce it. 

> The claims should be removed from the site, the readme, and the doc/Reproducible.md.

I disagree. Yes, there was an issue with the latest release on some newer Linux releases (possibly for example Ubuntu 22.0.4). This issue has been researched and solved. The build of the Sparrow Java code itself is fully reproducible as of 1.6.6. Only the copying of the JDK binaries was affected, and only because the behaviour of `objcopy` differed on newer Linux releases with regard to the stripping of debug information from the Java binaries. Building on Ubuntu 20.0.4 and earlier is fully reproducible.

**Comment by nyxnor** [comment]
> Yet you did manage to reproduce it.

Yes, hoping for an official release soon.

> I disagree. Yes, there was an issue with the latest release on some newer Linux releases (possibly for example Ubuntu 22.0.4).

All my tests are on latest debian 11.

I agree with the closing of this issue now that the beta was reproducible and and the next official release will possible be.
