### ISSUE TITLE
Proposal: Country specific decimal and thousands separators

### ISSUE THREAD

**Issue by tychsen** [sparrowwallet/sparrow#689]
Great Britain and the United States are two of the few places in the world that use a period to indicate the decimal place. Many other countries use a comma instead. The decimal separator is also called the radix character. Likewise, while the U.K. and U.S. use a comma to separate groups of thousands, many other countries use a period instead.

Right now it seems that Sparrow supports only the U.S./U.K. method (USD 4,254.41 vs. EUR 4.254,41).

This proposal consists of either:

- Country specific decimal and thousands separators based on system locale
- A setting under the preferences "General" tab

**Comment by tychsen** [comment]
Noted with thanks. And I agree - happy it is not disregarded totally.
On a note: I find it more valuable than translation.

**Comment by craigraw** [comment]
I've been rethinking this - it may actually be easier than I initially thought. Keeping the scope limited, it may be possible to add this relatively simply, and configure it as a menu item under the View menu. 

That said, I note that some European countries appear to use a space instead of a dot: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html. It's unclear to me whether this is actually common practice, and should be considered too.

**Comment by tychsen** [comment]
I know space is also used in some EU countries - I would add it when you anyways make the feature (unless it makes the solution unnecessarily much more complicated).

Setting is preferred over system locale as it seems less intrusive.

**Comment by RequestPrivacy** [comment]
As I might have some insights into the german speaking world (switzerland, germany, austria), I can assure you that normally a space OR a dot is used as a separator for thousands. Using both like in the example in the link (or see below) is uncommon - like I've never seen it.

German | 4 294 967.295,000

As far as for the german speaking world I would go with the dots but would always provide the comma of the decimal places so it's clear.

**Comment by tychsen** [comment]
Sorry, I didn't read that far into the table.

I have seen invoices from most of the world for the last 18 years. I only saw these 3 configs:

1. US: 1,234.56
2. EU 1: 1.234,56 (most common)
3. EU 2: 1 234,56

I agree with you. The site must be faulty.

**Comment by craigraw** [comment]
Added in 8fb6de85. Rather than try to autodetect, the user can select which combination of grouping and decimal separators they would prefer:

<img width="404" alt="Screenshot 2022-09-21 at 11 37 09" src="https://user-images.githubusercontent.com/862166/191471267-223839e2-4a94-495f-aef9-6938ffad8a0b.png">

**Comment by tychsen** [comment]
Nicely done.. Thanks!
