### ISSUE TITLE
[Feature] Provide automatic wiping of sparrow.log

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#696]
### Description
Sparrow provides logging output via the `sparrow.log` file. The output can be a bit verbose though as the call stacks are quite "line heavy".

This can amount to big log files, e.g. I have a file that was created roughly 1.5 months ago and already contains almost 200.000 lines and is 21MB in size.

### Solution
Provide a setting which enables to specify a time after which the log file is wiped.

**Comment by craigraw** [comment]
That's surprising large. Ideally the log file should not grow this fast under normal circumstances. Can you determine if there is a lot of repetition, and if so of what kind of errors?

**Comment by craigraw** [comment]
All of these are coming from the Whirlpool client, and as you note most likely Tor related. I'd be considering using a VPN instead of Tor at this point, although I know the privacy is not exactly the same. 

That said I'm considering suppressing exception logging for the third example you provided, which should reduce the problem dramatically.

**Comment by craigraw** [comment]
1 & 3 (of the examples provided above) have been suppressed in 6ad81e12. Hopefully this greatly reduces the Whirlpool connection logging output, so I'm going to close this issue off for now.
