### ISSUE TITLE
Windows Sparrow 1.6.6 Installer failing

### ISSUE THREAD

**Issue by cadayton** [sparrowwallet/sparrow#699]
Windows installer is failing for both Windows 11 and Windows 10.  Windows 10 indicated the code was not signed properly.   I did go through the manual process of validating the code and no issues.

The zip download after expanding has several files flagged with a creation year of 1980.  Makes me a little concerned about using the code.

**Comment by craigraw** [comment]
> Windows installer is failing for both Windows 11 and Windows 10. Windows 10 indicated the code was not signed properly.

It is not failing, it simply doesn't contain Windows code signing. Sparrow encourages the user to verify the download for themselves, rather than trust central authorities.

> The zip download after expanding has several files flagged with a creation year of 1980.

This date is specifically selected for reproducible build purposes. Arbitrary dates (for example from when the build was made) would result in non-reproducible builds.
