### ISSUE TITLE
An easier way to distinguish whether you are in mannet or in testnet 

### ISSUE THREAD

**Issue by 4rkad** [sparrowwallet/sparrow#711]
An easier way to distinguish whether you are in mannet or in testnet 

Often there is confusion whether you are using mainnet or testnet (especially for newbies). Maybe it would be interesting to indicate it in the wallet interface so that it would be easier to recognize which network we are using at any given time.

Please see sample image below (top right corner of the picture).

![Sparrow](https://user-images.githubusercontent.com/55397917/196029759-f9359115-5804-44cb-9e41-bac8a87500c2.jpg)

**Comment by Transisto** [comment]
> ...mainnet or testnet (especially for newbies).

How do newbies end up on testnet?

**Comment by 4rkad** [comment]
@Transisto Some people want to try first in testnet to know how works a tx in bitcoin

**Comment by 4rkad** [comment]
@craigraw yes, it's in an educational enviroment. I explain them it can be known if they click in tool menu and/or check the addresses list (tb1...)

**Comment by craigraw** [comment]
Added in b27709e9. If not on mainnet, Sparrow will display the network in the tab header on the right. The UI overhead is not too significant, and I think this is a useful distinguishing indicator particularly in an educational setting.

<img width="941" alt="Screenshot 2022-10-26 at 16 11 42" src="https://user-images.githubusercontent.com/862166/198049513-44ce9ef3-6f42-490a-ab30-8399d985434b.png">

**Comment by wnto** [comment]
Although this is closed, and to go into more detail into the following question:

> How do newbies end up on testnet?

1) During wallet workshops. I educate on Bitcoin and use testnet with newbies, so that learning Bitcoin does not depend on owning bitcoin. For that, the indication that @craigraw added in 2022 is sufficient. 

2) When being scammed. Besides the fake airdrop projects mentions by Jameson Lopp in https://blog.lopp.net/griefing-bitcoin-testnet/, scammers are selling more and more testnet bitcoin to unsuspecting newbies by instructing them to open sparrow in testnet mode (or even doing it for them), saying all the right things about Bitcoin and addresses, but not mentioning that the addresses the wallet is showing and the satoshis they are selling the victim are testnet and, therefore, worthless. 

For this reason, many wallets do add a prominent disclaimer like: "you are using a testnet wallet. coins you see here have zero economical value". 

Also, showing a value of Zero USD instead of the actual bitcoin value, or using tBTC or tSats instead would also make it more difficult for scammers to use Sparrow to rob uneducated victims and spoiling Bitcoin for them, maybe forever.

I created a testnet bitcoin wallet on Sparrow (English) today and didn't see any such disclaimers. I only saw the "testnet4" label after reading this thread.

Cheers!
