### ISSUE TITLE
Error Requesting Payjoin Transaction

### ISSUE THREAD

**Issue by DanGould** [sparrowwallet/sparrow#719]
Payjoin receiver error when Tor's not started. It would be nice to get a better error message (Error requesting payJoin transaction. could not connect to server. Check to see that tor is connected) and also see what endpoint I pasted in the UI

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/8525467/198074449-b5a6d3c0-384b-4703-89d5-7e0e41c58894.png">

After manually proxying Tor, I was able to establish 2 channels with 1 PayJoin!

https://twitter.com/bitgould/status/1585301587672473600

**Comment by craigraw** [comment]
Interesting use of Payjoin!

As I understand it, your Payjoin URI is an onion URL, and Sparrow is showing an error because Tor is not configured. I've added a check in 04a516d5 to handle this situation. Sparrow will also report a better error if the server returns a 404.

<img width="472" alt="Screenshot 2022-10-27 at 07 55 45" src="https://user-images.githubusercontent.com/862166/198205380-dc5c3532-1363-4dad-8a78-bd4e20e4474a.png">

**Comment by DanGould** [comment]
You are an animal Craig 🔥🔥🔥
