### ISSUE TITLE
Opening Wallet Shows No Transactions

### ISSUE THREAD

**Issue by st4rgut24** [sparrowwallet/sparrow#720]
Hi I have tried recovering my Sparrow wallet, using seed phrase and wallet files. I am able to see the wallet, but it says 'no transactions' as if I never used it before. I have double checked I entered everything correctly, and I do in fact see my transactions for a split second before it shows the message 'no transactions'. It has been a while since I last logged in and I am connected to a public server for transaction history. Please advise

**Comment by craigraw** [comment]
Are you using a passphrase? Check your passphrase is correct. If Sparrow detects that all the history it checks on loading the wallet has changed, it refreshes the whole wallet, which is why you see your transactions briefly before the refresh. An incorrect passphrase is the sole cause of this behaviour.

**Comment by st4rgut24** [comment]
ok I may have used an incorrect bip39 passphrase, will try again

**Comment by st4rgut24** [comment]
when entering the seed phrase, is the passphrase required?

**Comment by craigraw** [comment]
> when entering the seed phrase, is the passphrase required?

It's unclear what you mean. If you created a wallet with a passphrase, then yes you need to enter it every time.

Please note that Github issues are not the right place for support - use the Telegram group https://t.me/SparrowWallet for help.
