### ISSUE TITLE
Same labels are shown when using different bip39 passphrases

### ISSUE THREAD

**Issue by kaiwolfram** [sparrowwallet/sparrow#786]
I created a taproot wallet with bip39 passphrase, labeled the first address and closed the wallet.
Later I opened the wallet again, entered the wrong passphrase by mistake and send some sats to it because there was still my label that I set prior.

Showing the address labels even when entering the wrong passphrase is extremely misleading. Please consider showing no labels when entering different passphrases. The user assigns labels to addresses not indexes.

**Comment by craigraw** [comment]
Please see FAQ: https://sparrowwallet.com/docs/faq.html#all-my-addresses-have-changed

In particular, note that "Sparrow stores nothing in your wallet file that is derived from your passphrase". Given this, it is impossible for Sparrow to determine whether a different passphrase has been entered. This is intentional behaviour of BIP39, which for passphrase use combines something you have (a seed) with something you know (a phrase). Storing the passphrase (or something derived from it) would contradict this intention and weaken the security of this approach, making it easier to brute force.

BIP39 passphrase use is both a powerful and dangerous feature as a result, as the user must take responsibility for entering their passphrase correctly.
