### ISSUE TITLE
Dynamic whirpool Tx0 mixFeeTarget

### ISSUE THREAD

**Issue by searingGlamour685** [sparrowwallet/sparrow#895]
_Please correct me if I am fragrantly wrong and close the issue if my understanding is incorrect. I am not used to read Java so I might be alluciating._ 

**Background**
It seems Sparrow uses 3 of the block targets available from `Tx0FeeTarget`. Those are `MIN` (low priority), `BLOCKS_4` (medium priority) and `BLOCKS_2` (high priority).

These fees seem to be used for the Tx0 mining fee. However, these are not the ones used for the `mixFeeTarget` as these are hardcoded to use always `BLOCKS_4`:

https://github.com/sparrowwallet/sparrow/blob/258d46a2538ca42ddfb63a1576b92505a80b76a1/src/main/java/com/sparrowwallet/sparrow/whirlpool/Whirlpool.java#L151-L154

**Expected behaviour**
Expected behavior is that both Tx0 mining fee and Tx0MixFee change according to the priority slider (same as Samourai Wallet and Whirlpool GUI).

**Alternative solutions**
Alternatively, no one would complain about doing cheaper coinjoins. So the value could remain hardcoded but as `Tx0FeeTarget.MIN` instead of `Tx0FeeTarget.BLOCKS_4` on L152. Anyway, Sparrow seems to overpay on coinjoins for the little I have tested, so this should not impact user experience: but will save some Sats!

**Other context**
I did a few test to confirm my hypothesis. This fork of Sparrow seems to always create cheaper whirpool coinjoins (compared live side by side to Master branch): https://github.com/searingGlamour685/sparrow/pull/1

**Comment by rapidlab309** [comment]
I assume @craigraw coded it like that with the reason of:
1. Keep the UX as simple as possible of the average user
2. Save on unnecessary fees, as Tx0 confirmation is needed but the other aren't needed to be confirmed faster because Postmix UTXOs can be spent anyway with or without conformation
3. Whirlpool rounds may be confirmed even if `User A` set low fees, as long as `User B` set the necessary fees for current mempool business, as two (and sometimes even three) new users need to join in order to initiate Whirlpool TX.

**Comment by searingGlamour685** [comment]
Hey @rapidlab309 , thanks for the reply!

> 1. Keep the UX as simple as possible of the average user

The UI asks user to select a priority level anyway. If my understanding is correct, Sparrow then simply does not use the user's input later on. This fix does not add any UX complexity.

Points 2 and 3 reinforce the reasons to have a default for mixFeeTarget at `BLOCKS_24` target instead of `BLOCKS_4` and that's why I seemingly was able to build an Sparrow fork that does coinjoins just as well but cheaper in any mempool condition.

**Comment by rapidlab309** [comment]
Well, as someone who used GUI and love getting into details.. I could agree on the fact that adding a second slider or something similar to that is nice and making users to have more control over their TXs.

Having mixFeeTarget higher or lower is simply doesn't really matter, because the Whirlpool is already been done and you're able to use your UTXOs.. or just wait for it to confirm at some point. No rush is needed in here, and also saving some SATs too.

**Comment by craigraw** [comment]
I've been considering this, but I'm still undecided on if and how to change this for a better user experience. Note that Sparrow does not ignore the fee priority slider - it is used to determine the fee for the premix/tx0 transaction. It is the fee included in the premix outputs that is set to `BLOCKS_4`. It not clear to me that changing this `BLOCKS_24` would result in a better user experience - probably, it would result in many premix outputs getting "stuck" from the point of view of the user, since the coordinator needs to achieve a minimum amount of fees before the first mix round can take place. With a low fee set and an high fee rate environment, this might take days. 

This leads to considering adding an additional slider, or double use of the current slider. Neither are out of the question, but adding an additional slider would probably be confusing to most users. The mechanics of how the coordinator works when choosing UTXOs are too complex (satisfying both `minRelayFee` and `minNbTxs`) for a simple explanation in order to make user selection of such a control a straightforward task. To be clear, I am concerned that without guidance, many users will simply opt for minimum fees and end up with a Whirlpool client that appears "broken" as they wait for an indeterminate time for their first mix to take place. Here's how that interface might look - not, in my view, very approachable for first timers:

<img width="712" alt="Screenshot 2023-03-20 at 11 32 08" src="https://user-images.githubusercontent.com/862166/226299977-f44c5ec4-1575-4c45-8b75-d8d58d201de7.png">

Probably then the simplest option is to have the premix priority slider affect both `tx0FeeTarget` and `mixFeeTarget` - again however I'm not sure how clear that is, and I'm concerned about affecting the overall user experience and increasing the support burden.

**Comment by RequestPrivacy** [comment]
Without a small picture describing the whirlpool process (which fee is used at which time) the dialog will confuse the hell out of users. 

I mean I thought I understood whirlpool but even I'm confused rn: 

> The mechanics of how the coordinator works when choosing UTXOs are too complex (satisfying both minRelayFee and minNbTxs) for a simple explanation in order to make user selection of such a control a straightforward task.

My understanding was that one chooses 1 of the priorities and ALL premix utxos of ALL users of that priority are treated equal by the coordinator and get picked randomly (even if individual fees "attached" to the premix utxos might differ slightly).

That being said: I learned something out of this issue and so could people seeing the dialog in their Sparrow Wallet. Maybe add a schematic picture of the whirlpool process  at the side? With a caution symbol appearing once a user selects the "Low" first mix priority?

**Comment by craigraw** [comment]
Adding more text and images doesn't necessarily make things easier - it can have the opposite effect. I am not particularly keen to make this process any more complex that it needs to be (which is where things are right now imo).

Note the coordinator does treat all UTXOs equally (in other words, at random) - but if the selection it makes does not meet the required `minRelayFee`, it will need to pick again. This will inevitably mean that UTXOs with a higher available amount for fees get preferred (in general) in a high/variable fee rate environment. To what extent this is true depends on how quickly actual fee rates change versus predicted values.

**Comment by craigraw** [comment]
It's variable, but currently seems to be around 1000 sats per output difference (this at 12 to 20 sats/vB for a medium priority spend)

**Comment by craigraw** [comment]
Ok, I've decided to use the Premix Priority slider to change both `tx0FeeTarget` and `mixFeeTarget`. If however the low priority fee rate is less than half the normal priority fee rate, Sparrow will show a warning indicating the first mix may be delayed:

<img width="712" alt="Screenshot 2023-03-21 at 09 21 04" src="https://user-images.githubusercontent.com/862166/226542877-e4d06acc-dbe4-428b-b12c-eb4f3aa63436.png">

98b33e18

**Comment by searingGlamour685** [comment]
Thank you for taking a look at this @craigraw

> Ok, I've decided to use the Premix Priority slider to change both `tx0FeeTarget` and `mixFeeTarget`. If however the low priority fee rate is less than half the normal priority fee rate, Sparrow will show a warning indicating the first mix may be delayed:

I believe too this is indeed the best compromise between control, accuracy and simplicity. Great fix :clap: 

We can clearly identify the root cause of this issue: the first mix in WP suffers of "free riding" problem. No one wants to be the subsidizer. Paying higher fees, might result on a faster coinjoin, but you will still be dependant on the fees other users pay (so the relationship is not linear or predictable). Of course, explaining this issue on the Sparrow UI is out of the question, too complex. The decision that was taken by fixing to `BLOCKS_4` before this fix meant that _in average_ the Sparrow user partially subsidizes the premix of SW / Whirlpool GUI users that do opt to a lower priority. 

With this fix, even if users might not get the full context of what is going on, they have the choice themselves (and the risk of low priority is well outlined). Those who understand what is going on, will gladly now evaluate using Sparrow over the other whirlpool clients knowing they now have access to "the same whirlpool deals".
