### ISSUE TITLE
UI/UX Proposal: Animated QR scan progression visualisation

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#924]
When scanning parts of an animated QR using Sparrow Wallet visual feedback is missing from scan 2 and forward:

https://youtu.be/qQPQvUzMlDs

For scanning of ordinary animated QRs the visual feedback isn't that important - and since it's unknown to Sparrow how many scans it will take to understand the full descriptor today's progress bar (animation?) works fine. But when the user needs to switch between several physical steel plates with QRs (in order to make up one total descriptor) the missing feedback in the progress bar make the user doubt if QR #2 and onward are scanned correctly.

We propose to indicate a correct scanned QR by flashing the cam and adding a counter (or something like that). See mock-up solely for understanding, not thought through design:

https://youtu.be/u3qjFm_P6l0

There can be other great ways to indicate the success of a scan.

**Comment by craigraw** [comment]
The Blockchain Commons UR specification uses fountain encoding. A fountain code is a way to take some data and transform it into an effectively unlimited number of encoded chunks, such that you can reassemble the original data given any subset of those chunks, as long as you have a little more than the size of the original file. This allows for decoding to start at any point, and for missed frames to not require the entire sequence to need to be repeated.

This is of course ideal for device to device communication, but less ideal in your application. It is probable here that the final elements of data that are required to complete the scan are contained piecemeal in the last few codes. There are also multiple codes being scanned in the same image.

I suggest simply making the QR larger and more dense so it can be represented in a single frame, as Sparrow does when it creates the PDF export (see the show QR button next to the Descriptor field on the Settings tab).

**Comment by seedhammer** [comment]
It is not possible to make the QRs larger due to the physical restrictions of the steel plates.

See: https://seedhammer.com/article/the-seedhammer-metal-plates (SH02 and SH03)

A full descriptor in a single frame is not realistic. Even if it was it would take way too long to hammer it and readability from steal is impossible.

**Comment by craigraw** [comment]
Sparrow also supports the Specter approach, which uses a series of QR codes that need to be in a specific order and scanned from start to finish, for example 3 QRs in a sequence
```
p1of3 <data1>
```
```
p2of3 <data2>
```
```
p3of3 <data3>
```

where <data> is interpreted as a string of characters (in this case, a fragment of the full output descriptor). When all the parts have been received, the strings are concatenated.  Does this work better for your application?

**Comment by craigraw** [comment]
This seems like a useful goal - for multisig wallets, making a backup of the output descriptor is important, but so is protecting it for privacy.

Can I suggest looking at the Blockchain Commons SSKR specification? It seems to be a good fit for what you are trying to achieve, given (as I understand it) the secret can be any data: https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md

It's also good to be using a published standard for this - it's reassuring for users.

**Comment by RvWensen** [comment]
Hi @craigraw,

What @seedhammer means is that it is clear through the animation that the first qr code has been scanned, but if several qr codes have to be scanned, the animation remains still, it is not clear whether 2nd, 3rd, etc etc has been scanned.

I personally find that very difficult, I would like to see when or whether the subsequent qr codes have also been scanned.

Thanks for making this awesome software!

Regards.

**Comment by mineracks** [comment]
I agree with SeedHammer and RvWensen above - love the workflow we can now get with ther combination of sparrow + seed signer + seedhammer
The current Sparrow UX for loading the descriptor from the steel plates could be slicker - I know it eventually works after you show it both plates in a 2 of 3 for example, but you have to guess at what's happening because the progress bar doesn't give you an accurate indication of how much of the wallet descriptor data has so far been successfully read by Sparrow.

**Comment by craigraw** [comment]
I've amended the progress count to only increment when a unique fountain code is received. Although as discussed the progress bar is only an indication and not an absolute due to the nature of fountain codes, the progress bar will now only move forward upon scanning a unique code (and not for a repeat scan of one it has already seen, as was the case). 

Implemented in 29b630f6 - hopefully this resolves the issue?

**Comment by craigraw** [comment]
No response, closing this off as solved.

**Comment by RvWensen** [comment]
I don't know how to test it without it being introduced in the main version it wasn't before, is it now? Then I will test it for you right away.

**Comment by craigraw** [comment]
> is it now?

Yes

**Comment by RvWensen** [comment]
It works a lot better! Now it is very workable.

One point of feedback, I don't know if you can know in advance how many need qr's to be scaned, but if you did, the following would be cool;

I have now tested it with a multi sign of 3/5, for this I had to scan 6 qr codes. 
There are two on each engraved iron plate.

It would be nice, but this would be ONLY an aesthetic issue if with every scanned qr the bar gets 16.66667% extra fill. So that once all 6 items are scanned it will be 100%.

Again as it is now, chapeau. 
I sent you a donation as a thank you for the great work already done, and also super fast!
