### ISSUE TITLE
Unexpected end of script for very big transaction

### ISSUE THREAD

**Issue by ottosch** [sparrowwallet/sparrow#948]
When restoring a testnet wallet, I kept getting the following exception, which prevented me from restoring the wallet:
```
ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.drongo.protocol.ProtocolException: Unexpected end of script
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Script.parse(Unknown Source)
```
Message in wallet:
```
Error loading transactions: Unexpected end of script
```

From my debugging, it seems this is caused by txid [d2041eb9ae42969ca9437b3a225ec88750321485acb426b2a5db7d651e2155da](https://mempool.space/testnet/tx/d2041eb9ae42969ca9437b3a225ec88750321485acb426b2a5db7d651e2155da?showFlow=false#flow) (1 of 20,000 multisig) at path `m/84'/1'/0'/0/19`.

Xpub:
```
vpub5YVHy2Rnk6cLGRfJLkq6fNgDb45eJHh9U6nNjMqAg9qXU4EW6Bj5REk1NgusJymoQHnPE87d5kNB8r9CPGARRLW9jj7XjQiZ3pFuZbN6p6G
```

Edit: as a suggestion, the wallet could skip problematic transactions (printing a warning) and continue syncing.

PS: the wallet has premix, postmix and bip47 transactions, but not sharing the xpubs since those are loaded correctly.

**Comment by craigraw** [comment]
The issue here is that the script in the transaction is actually not valid. Most of the large script is a repetition of the bytes `2103ff27279c2e8aaf6f8cf7f92172e9979be1bdb53bc74085c905be00319cd5c0c7` but at the very end of the script, the bytes `4e71ae` appear.

This is `OP_PUSHDATA4` (`0x4e`) which should be followed by 4 bytes of data. In this case, there are only 2 bytes (`0x71ae`), making the script technically invalid. I'm actually surprised this was allowed - it seems some degree of leniency is allowed.

Given this it makes sense for Sparrow to have some leniency as well. From https://github.com/sparrowwallet/drongo/commit/a8df17ff5eb906cf1d929f978fdad34bb244ce55, Sparrow will continue with transaction parsing if an invalid OP_PUSHDATA opcode is found, using whatever part of the script it has managed to parse before this point.
