### ISSUE TITLE
Question | Feature Request: Mixing multiple postmix wallets to the same Mix To Wallet cold storage target

### ISSUE THREAD

**Issue by jasonpearce** [sparrowwallet/sparrow#955]
Regarding [Mixing to cold storage](https://sparrowwallet.com/docs/mixing-whirlpool.html#mixing-to-cold-storage), does Sparrow support mixing multiple open postmix output wallets to the same Mix To Wallet target?

Scenario
The following wallets are open in Sparrow:

- Wallet A: Multisig Cold Storage
- Wallet B: Postmix CoinJoin of 0.100 with a Mix To Wallet target of Wallet A
- Wallet C: Postmix CoinJoin of 0.010 with a Mix To Wallet target of Wallet A

Is it safe to have both Wallet B and Wallet C configured to use the same Mix To Wallet target of Wallet A? Will Wallets B and C be aware of used addresses (addresses either wallet could use) and avoid address reuse in Wallet A? Or is there a risk that they will each start mixing to the same addresses in Wallet A?

If multiple open wallets can safely share the same Mix To Wallet target of Wallet A, is there a limit on how many postmix output wallets can share the same Mix To Wallet?

Lastly, are there any other risks or concerns that should be considered before configuring multiple postmix output wallets to use the same shared mix-to-wallet target?

Thank you for a great wallet and potential comments.

**Comment by craigraw** [comment]
There is a risk that Wallet B and Wallet C will mix to the same address. It's a small risk, and will probably never happen, but if both have mix rounds that occur at exactly the same time they will pick the same destination address. 

The solution here is to use one mixing wallet instead of two - but I assume there is a reason you want separate wallets.
