### ISSUE TITLE
Tx stuck unconfirmed

### ISSUE THREAD

**Issue by vetronz** [sparrowwallet/sparrow#959]
Has anyone encountered bug whereby transactions get 'stuck' unconfirmed?

I have an issue whereby a 2 of 3 multi-sig wallet can receive incoming tx, and can sign outgoing tx but the funds get 'stuck' and remain unconfirmed for days.

Here are a couple of the tx ids for reference:
a2ed60dc31748fdce1a65dbe740a55bbc2b8fc806324d52d79ecd32ff4d0feda
53a84fe4c940d4725295ad0d7026f8a712b587e3ec07c5c0399ba1d1aa774265

If I inspect the tx in sparrow wallet I see 'insufficient funds!' under the amount, but the wallet has the funds for the transfer.

Version: Sparrow Wallet 1.7.6
Pop!_OS 22.04 LTS x86_64

Help appreciated.

**Comment by craigraw** [comment]
Unconfirmed transactions are simply not yet included in the blockchain, because miners select the transactions paying the greatest fees first, and your transactions have a lower fee rates than others. For example, the first transaction above has a fee rate of under 50 sats/vb, and the going fee rate for inclusion into the next block is currently over 200 sats/vb. 

You will either need to wait for the mempool to reduce, or use RBF or CPFP to increase the fee rate of these transactions.

**Comment by vetronz** [comment]
Hi Craig

Yeah i think you're right!

I had no idea transaction fees had gone that high.

Let me know if I need to do anything to mark this thread as closed.
