### ISSUE TITLE
stuck transaction, can't bump fee or cancel

### ISSUE THREAD

**Issue by OrangeGrasshopper** [sparrowwallet/sparrow#966]
I selected a 1M sat utxo and hit the mix selected button. chose the pool then start mix. But its been stuck awhile now in the pre-mix wallet with an unconfirmed parent message, and when I try to  bump the fee I keep getting a failed to broadcast error. 
Error broadcasting transaction com.sparrowwallet.sparrow.net.ServerException: Retries exhausted

also this error
RpcError { code: -25, message: \"bad-txns-inputs-missingorspent\", data: None }","id":1291,"jsonrpc":"2.0"}

Originally connected to my electrum server through embassy so through tor, but when that failed I reconnected to my local bitcoin node without tor but the transactions still failed to broadcast. 

unsure how to proceed. evidently I didn't pay enough fees the first time. If the fee environment goes back to normal will it finally confirm? I'm just not sure why I couldn't bump the fee using the CPFP option where I raised the fee to 70 sats/vb. 

let me know if you need more of the log files
thanks for looking

**Comment by craigraw** [comment]
Probably the best advice here is to just wait a little - mempools have been busier over weekends of late, but fee rates are trending downwards and the premix transaction should be confirmed soon. Using CPFP will mean that the premix outputs won't be able to take part in a mix (since they are already spent). Mixing takes time anyway, so practically not much is lost by a short delay, and the transaction will likely be confirmed within a week.
