### ISSUE TITLE
proposal: consider switching to the zbar QR code scanning library

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#967]
We originally used the zxing QR code scanner because there was a pure Go port. However, from our experimentation it became clear that the zbar library has superior scanning performance for difficult targets such as QR codes on lower contrast steel plates.

We see similar difficulties in scanning performance from Sparrow, even though (presumably) desktop webcams are better quality than the $5 rpi cameras used in the seedsigner "orange pill" hardware setup. For example, the rpi camera has a fixed focus whereas desktop webcams don't.

Therefore, we propose that Sparrow switch to the zbar library. The upside is better scan performance; the downside is that the Java port is JNI based. However, I believe Sparrow already includes native code for other uses, right?

**Comment by craigraw** [comment]
Given the number of platforms Sparrow supports I'd like to try avoid adding additional native dependencies - they are often the source of problems given a wide range of devices. But I'll look into zbar - if it's truly a marked improvement, it may be worth it.

**Comment by hansmade1** [comment]
I recently got some SeedHammer plates for a 2/3 multisig backup.  I was able to scan the pkey QRs with seedsigner but have been unsuccessful scanning the descriptor QRs into Sparrow. I have tried everything to register a scan of the descriptor QR.  A Logitech webcam on a cable, my quite new Dell laptop camera, taking a photos with iPhone in aeroplane mode, editing , cropping increasing contrast etc.  then presenting the phone screen to the camera, all manner of lighting and magnifying including natural light.  Nothing has worked even though I get very good looking images boxed into the dotted lines.   Apparently the scans register ok on a Mac but so far proving very difficult on windows and an older laptop running Linux mint.  I hope an update in the Sparrow software will improve resolve this issue.

**Comment by craigraw** [comment]
@hansmade1 See #968 - I assume your QRs are inverted.

**Comment by hansmade1** [comment]
> @hansmade1 See #968 - I assume your QRs are inverted.

It depends on the light.  I made some prints of photos today edited to have inverted and not.  The not inverted ie light background, worked

**Comment by seedhammer** [comment]
@hansmade1 : Have you tried Nunchuk wallet? They use the iPhones camera in such a way that it scans very good.

@craigraw - Sparrow also gives the opportunity to use your iPhone as a satellite scanner when using Sparrow on a Mac. However, it does not scan - assume it is because of the zxing QR code scanner used by Sparrow. We still push for a move to the zbar library.

**Comment by craigraw** [comment]
@seedhammer Can you capture an image that scans with zbar, but does not scan with zxing?

**Comment by tadeubas** [comment]
I always have some problems when trying to scan QR codes, the big ones are the worst. I tried two webcams and they reverse the image and show little dots in the QR code, sometimes I have to use this [Python tool](https://github.com/pythcoiner/SeedQReader) to scan the big QR code and create a sequence of small ones, in order to make Sparrow read it!

Here is an example of what my webcam shows, the Python tool reads it right away! But plz, try this with Sparrow 👇 

QRCode from Windows camera:
![WIN_20230630_19_48_46_Pro](https://github.com/sparrowwallet/sparrow/assets/5518496/11d98d50-4673-483b-8f19-cc4344b7d010)

QRCode from Sparrow camera:
![what-sparrow-sees](https://github.com/sparrowwallet/sparrow/assets/5518496/10be5262-efd7-48d8-90a5-0668c540993a)

**Comment by craigraw** [comment]
@tadeubas I notice that you are not using HD capturing - does neither webcam support it?

Thanks for linking the SeedQReader project - it uses zbar so will be useful to test differences from zxing.

**Comment by tadeubas** [comment]
When I try to click on the "Use HD Capture" for this camera, Sparrow freezes for about 35 seconds and then show a black screen 👇 

SO is Windows 11, Sparrow 1.7.7

![image](https://github.com/sparrowwallet/sparrow/assets/5518496/26830b10-7a28-436b-99c8-e4918059c9a3)

**Comment by craigraw** [comment]
I have spent a week looking into this, and there is both good and bad news.

The good news is that zbar does show better performance when scanning blurry QR codes. I tested across a range of devices (Seedsigner, Jade, Passport Founders Edition) and found that often zbar would find a QR code when zxing did not. I've tried to improve zxing's abilities in this regard without success.

The bad news is that it appears zbar/JNI is difficult to compile for all platforms. In particular, it is not at all well suited to Windows. I've tried for several days to get `libzbar-0.dll` and `libzbarjni-0.dll` compiled using a variety of build environments - it just doesn't seem to be possible to get working binaries, since they all end with dependencies on the Linux flavoured build environment libraries that are required to get a build done. The precompiled Windows binaries shipped at https://github.com/mchehab/zbar/releases are the same, don't even run on a normal Windows system. If anyone else is prepared to give it a go, there is a demo project at https://github.com/craigraw/zbar-java. It's also not possible to produce working binaries for old Macs still running Catalina - the reason for this is less clear.

Given this I'm still weighing the risk of including it. There is certainly a possibility of hard crashes with any native code, and particularly native code that is old and poorly maintained such as zbar. If anyone is prepared to test a beta build, that would help to some extent to determine viability. If so please let me know below what download you use to install Sparrow.

**Comment by tadeubas** [comment]
I've been using the .EXE file on Windows 11 `Sparrow-1.7.7.exe`

**Comment by seedhammer** [comment]
We can test the macOS builds (m1 and Intel).

**Comment by craigraw** [comment]
Update: I've managed to address both the Windows and the older Mac issues I mentioned, so zbar scanning is now available across all platforms Sparrow is supported on.

I've uploaded a Sparrow beta build with zbar to https://github.com/craigraw/beta/releases/tag/1.7.8-zbar

When you test it, please check end of the Sparrow log (see Help menu) to see if there are any issues loading the zbar library.

**Comment by hansmade1** [comment]
Well done Craig,  I was able to scan all 3 Seedhammer plates relatively quickly on my windows 10 PC.  There are no issues recorded in the log file.

**Comment by seedhammer** [comment]
This is awesome. We will test as well now.

**Comment by seedhammer** [comment]
Scanning from Sparrow works remarkable better now. SeedHammer plates scan much easier.

Thank you for taking our request serious.

**Comment by tadeubas** [comment]
I've tested 1.7.8-zbar on Win 11 trying to scan my monitor with daylight from my window:
* Mnemonic Words (scan QR...)
* SeedSigner (XPUB QR)
* Specter DIY (ZPUB QR)
* Send > Pay to (address Scan)

Scan MUCH FASTER NOW, no need to struggle with trying to align the camera and hold still.For me, this was the best Sparrow update for a long time!

I will update this comment at night with artificial light!

**Comment by craigraw** [comment]
Thanks for all the testing. Closing this off.
