### ISSUE TITLE
Transaction hex tooltips

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#98]
It would be amazing to be able to hover and access explanations about each highlighted section of the TX hex.

op codes, scripts, hex versions of addresses, etc.

This would help understand the hex content so much better!

I can help at pulling in citations and research titles and short explanations:

- https://en.bitcoin.it/wiki/Script
- https://learnmeabitcoin.com/explorer/transaction/31522a45982c007ee939697a92d54a30dc60be16239f6f610b0e6eb58a430e25/output/0#scriptPubKey

<img width="1049" alt="Screen Shot 2021-04-09 at 11 22 45 AM" src="https://user-images.githubusercontent.com/807505/114204446-352f5200-9927-11eb-8a80-e8ac35190bff.png">

**Comment by craigraw** [comment]
Implemented in 2c98c86. The tooltips describe the span of the highlighted hex (script opcodes are pulled out in the respective fields of the transaction viewer).

I've kept the tooltips short in order to not obscure too much of the transaction hex below. Happy to consider longer descriptions if they are well written, but there is value in keeping it light and to the point.

**Comment by craigraw** [comment]
Closing this off for now.
