### ISSUE TITLE
Key order not respected under text-export of descriptor

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#985]
1. Restore a multisig wallet with this descriptor (New Wallet -> paste it in Script Policy -> "Edit"):
`wsh(sortedmulti(2,[dc567276/48h/0h/0h/2h]xpub6DiYrfRwNnjeX4vHsWMajJVFKrbEEnu8gAW9vDuQzgTWEsEHE16sGWeXXUV1LBWQE1yCTmeprSNcqZ3W74hqVdgDbtYHUv3eM4W2TEUhpan,[f245ae38/48h/0h/0h/2h]xpub6DnT4E1fT8VxuAZW29avMjr5i99aYTHBp9d7fiLnpL5t4JEprQqPMbTw7k7rh5tZZ2F5g8PJpssqrZoebzBChaiJrmEvWwUTEMAbHsY39Ge,[c5d87297/48h/0h/0h/2h]xpub6DjrnfAyuonMaboEb3ZQZzhQ2ZEgaKV2r64BFmqymZqJqviLTe1JzMr2X2RfQF892RH7MyYUbcy77R7pPu1P71xoj8cDUMNhAMGYzKR4noZ))`
2. Notice how the keystores are ordered; Keystore1: dc567276, Keystore2: f245ae38, Keystore3: c5d87297.
3. Press "Apply" and now show the descriptor (click "Edit" under Script Policy).
4. It now looks like this:
`wsh(sortedmulti(2,[dc567276/48h/0h/0h/2h]xpub6DiYrfRwNnjeX4vHsWMajJVFKrbEEnu8gAW9vDuQzgTWEsEHE16sGWeXXUV1LBWQE1yCTmeprSNcqZ3W74hqVdgDbtYHUv3eM4W2TEUhpan/<0;1>/*,[c5d87297/48h/0h/0h/2h]xpub6DjrnfAyuonMaboEb3ZQZzhQ2ZEgaKV2r64BFmqymZqJqviLTe1JzMr2X2RfQF892RH7MyYUbcy77R7pPu1P71xoj8cDUMNhAMGYzKR4noZ/<0;1>/*,[f245ae38/48h/0h/0h/2h]xpub6DnT4E1fT8VxuAZW29avMjr5i99aYTHBp9d7fiLnpL5t4JEprQqPMbTw7k7rh5tZZ2F5g8PJpssqrZoebzBChaiJrmEvWwUTEMAbHsY39Ge/<0;1>/*))#r0zddq4q`

It is expected that the script policy key order (`wsh(sortedmulti(2,Keystore1,Keystore2,Keystore3))`) is to be respected.

**Comment by seedhammer** [comment]
Thank you. Some (minor?) points that may or may not sway your decision:

1. The animated QR code export of the descriptor does not sort the keys, and outputs them in the order of the key tabs below. At minimum, that seems like an inconsistency.
2. As a side-effect of the sorting, if you restore a multisig wallet by pasting a text descriptor from Sparrow the order of the tabs will differ from the original wallet.
3. While I understand the need to have a consistent descriptor among co-signers, I think that's a lost cause because there are other variations. Not only the key order that this issue is about, but also whether the descriptor includes child derivation paths ("/<0;1>/*") or not. In general, it's hard to tell whether two descriptors are equivalent from just eye-balling them.

FWIW, in our next release we're switching the descriptor information view to display receive and change addresses; they match exactly for two equivalent descriptors, and they will dramatically differ if the descriptors are not equivalent.

**Comment by craigraw** [comment]
> The animated QR code export of the descriptor does not sort the keys, and outputs them in the order of the key tabs below. At minimum, that seems like an inconsistency.

You're right, this is inconsistent. Fixed in 50aa9b4d. 

Fixing this gave me a chance to review the sort implementation. When presented with a key expression with wildcard elements (as is the case here), Sparrow uses the first (0th) index of each wildcard to derive a key to perform the lexicographic sort on. This seemed the most rational approach.

> As a side-effect of the sorting, if you restore a multisig wallet by pasting a text descriptor from Sparrow the order of the tabs will differ from the original wallet.

I agree this is non-ideal - unfortunately, this appears to me to be one of those cases where there is no perfect solution. After giving it quite a lot of thought I decided a canonical representation was the lesser of the evils, given the keystores can be added in any order anyway.

> While I understand the need to have a consistent descriptor among co-signers, I think that's a lost cause because there are other variations. Not only the key order that this issue is about, but also whether the descriptor includes child derivation paths ("/<0;1>/*") or not.

Let's not admit defeat just yet :)

In particular, multipath descriptors using the `<0;1>` format are becoming increasingly widespread, and are certainly the technically correct way of encoding a BIP32 HD wallet as a single descriptor. The next version of Sparrow will support reading them in QRs as per the `child-pair-component` encoding [recently added](https://github.com/BlockchainCommons/Research/commit/f966a0513217a345a202f8c0570e03f794333dc2) to the `crypto-hdkey` UR specification. I won't output descriptor QRs using this format just yet, but it's worth adding support for this if you haven't already.

> FWIW, in our next release we're switching the descriptor information view to display receive and change addresses; they match exactly for two equivalent descriptors, and they will dramatically differ if the descriptors are not equivalent.

That's a good approach as well.
